CREATE DATABASE DbsWzsk;
USE DbsWzsk;

CREATE USER 'mpsitech'@'%' IDENTIFIED BY 'asdf1234';
GRANT ALL PRIVILEGES ON DbsWzsk.* TO 'mpsitech'@'%';

CREATE USER 'mpsitech'@'localhost' IDENTIFIED BY 'asdf1234';
GRANT ALL PRIVILEGES ON DbsWzsk.* TO 'mpsitech'@'localhost';

DROP TABLE IF EXISTS TblWzskAccRMUserUniversal;
DROP TABLE IF EXISTS TblWzskAMPersonDetail;
DROP TABLE IF EXISTS TblWzskAMShotPar;
DROP TABLE IF EXISTS TblWzskAMUserAccess;
DROP TABLE IF EXISTS TblWzskAMUsergroupAccess;
DROP TABLE IF EXISTS TblWzskAVControlPar;
DROP TABLE IF EXISTS TblWzskAVKeylistKey;
DROP TABLE IF EXISTS TblWzskAVValuelistVal;
DROP TABLE IF EXISTS TblWzskCFile;
DROP TABLE IF EXISTS TblWzskHistRMUserUniversal;
DROP TABLE IF EXISTS TblWzskJAVKeylistKey;
DROP TABLE IF EXISTS TblWzskJMObjgroupTitle;
DROP TABLE IF EXISTS TblWzskJMPersonLastname;
DROP TABLE IF EXISTS TblWzskJMUserState;
DROP TABLE IF EXISTS TblWzskMFile;
DROP TABLE IF EXISTS TblWzskMObject;
DROP TABLE IF EXISTS TblWzskMObjgroup;
DROP TABLE IF EXISTS TblWzskMPerson;
DROP TABLE IF EXISTS TblWzskMSession;
DROP TABLE IF EXISTS TblWzskMShot;
DROP TABLE IF EXISTS TblWzskMUser;
DROP TABLE IF EXISTS TblWzskMUsergroup;
DROP TABLE IF EXISTS TblWzskRMUsergroupUniversal;
DROP TABLE IF EXISTS TblWzskRMUserMUsergroup;

DROP TABLE IF EXISTS TblWzskQFilList;
DROP TABLE IF EXISTS TblWzskQObjList;
DROP TABLE IF EXISTS TblWzskQObjRef1NFile;
DROP TABLE IF EXISTS TblWzskQOgr1NObject;
DROP TABLE IF EXISTS TblWzskQOgr1NShot;
DROP TABLE IF EXISTS TblWzskQOgrList;
DROP TABLE IF EXISTS TblWzskQOgrSup1NObjgroup;
DROP TABLE IF EXISTS TblWzskQPreselect;
DROP TABLE IF EXISTS TblWzskQPrsADetail;
DROP TABLE IF EXISTS TblWzskQPrsList;
DROP TABLE IF EXISTS TblWzskQSelect;
DROP TABLE IF EXISTS TblWzskQSes1NShot;
DROP TABLE IF EXISTS TblWzskQSesList;
DROP TABLE IF EXISTS TblWzskQShtAPar;
DROP TABLE IF EXISTS TblWzskQShtList;
DROP TABLE IF EXISTS TblWzskQShtRef1NFile;
DROP TABLE IF EXISTS TblWzskQUsgAAccess;
DROP TABLE IF EXISTS TblWzskQUsgList;
DROP TABLE IF EXISTS TblWzskQUsgMNUser;
DROP TABLE IF EXISTS TblWzskQUsr1NSession;
DROP TABLE IF EXISTS TblWzskQUsrAAccess;
DROP TABLE IF EXISTS TblWzskQUsrList;
DROP TABLE IF EXISTS TblWzskQUsrMNUsergroup;

CREATE TABLE TblWzskAccRMUserUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMUser BIGINT UNSIGNED,
	unvIxWzskVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixWzskVRecaccess INT UNSIGNED,
	INDEX (refWzskMUser),
	INDEX (unvIxWzskVMaintable),
	INDEX (unvUref)
) ENGINE = INNODB;

CREATE TABLE TblWzskAMPersonDetail(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMPerson BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(192),
	INDEX (refWzskMPerson)
) ENGINE = INNODB;

CREATE TABLE TblWzskAMShotPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMShot BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (refWzskMShot),
	INDEX (x1SrefKKey)
) ENGINE = INNODB;

CREATE TABLE TblWzskAMUserAccess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMUser BIGINT UNSIGNED,
	x1IxWzskVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWzskWAccess INT UNSIGNED,
	INDEX (refWzskMUser),
	INDEX (x1IxWzskVFeatgroup),
	INDEX (x2FeaSrefUix)
) ENGINE = INNODB;

CREATE TABLE TblWzskAMUsergroupAccess(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMUsergroup BIGINT UNSIGNED,
	x1IxWzskVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWzskWAccess INT UNSIGNED,
	INDEX (refWzskMUsergroup),
	INDEX (x1IxWzskVFeatgroup),
	INDEX (x2FeaSrefUix)
) ENGINE = INNODB;

CREATE TABLE TblWzskAVControlPar(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ixWzskVControl INT UNSIGNED,
	x1RefWzskMUser BIGINT UNSIGNED,
	x2IxWzskVLocale INT UNSIGNED,
	Par VARCHAR(192),
	Val VARCHAR(192),
	INDEX (ixWzskVControl),
	INDEX (x1RefWzskMUser),
	INDEX (x2IxWzskVLocale),
	INDEX (Par)
) ENGINE = INNODB;

CREATE TABLE TblWzskAVKeylistKey(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	klsIxWzskVKeylist INT UNSIGNED,
	klsNum INT UNSIGNED,
	x1IxWzskVMaintable INT UNSIGNED,
	x1Uref BIGINT UNSIGNED,
	Fixed TINYINT,
	sref VARCHAR(50),
	Avail VARCHAR(1024),
	Implied VARCHAR(1024),
	refJ BIGINT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (klsIxWzskVKeylist),
	INDEX (klsNum),
	INDEX (x1IxWzskVMaintable),
	INDEX (x1Uref),
	INDEX (sref)
) ENGINE = INNODB;

CREATE TABLE TblWzskAVValuelistVal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	vlsIxWzskVValuelist INT UNSIGNED,
	vlsNum INT UNSIGNED,
	x1IxWzskVLocale INT UNSIGNED,
	Val VARCHAR(192),
	INDEX (vlsIxWzskVValuelist),
	INDEX (vlsNum),
	INDEX (x1IxWzskVLocale)
) ENGINE = INNODB;

CREATE TABLE TblWzskCFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
) ENGINE = INNODB;

CREATE TABLE TblWzskHistRMUserUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMUser BIGINT UNSIGNED,
	unvIxWzskVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixWzskVCard INT UNSIGNED,
	ixWzskVPreset INT UNSIGNED,
	preIxWzskVMaintable INT UNSIGNED,
	preUref BIGINT UNSIGNED,
	start INT UNSIGNED,
	INDEX (refWzskMUser),
	INDEX (unvIxWzskVMaintable),
	INDEX (unvUref),
	INDEX (ixWzskVCard),
	INDEX (ixWzskVPreset),
	INDEX (preIxWzskVMaintable),
	INDEX (preUref)
) ENGINE = INNODB;

CREATE TABLE TblWzskJAVKeylistKey(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskAVKeylistKey BIGINT UNSIGNED,
	x1IxWzskVLocale INT UNSIGNED,
	Title VARCHAR(192),
	Comment TEXT,
	INDEX (refWzskAVKeylistKey),
	INDEX (x1IxWzskVLocale)
) ENGINE = INNODB;

CREATE TABLE TblWzskJMObjgroupTitle(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMObjgroup BIGINT UNSIGNED,
	x1IxWzskVLocale INT UNSIGNED,
	Title VARCHAR(100),
	INDEX (refWzskMObjgroup),
	INDEX (x1IxWzskVLocale),
	INDEX (Title)
) ENGINE = INNODB;

CREATE TABLE TblWzskJMPersonLastname(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMPerson BIGINT UNSIGNED,
	x1Startd INT UNSIGNED,
	Lastname VARCHAR(50),
	INDEX (refWzskMPerson),
	INDEX (x1Startd),
	INDEX (Lastname)
) ENGINE = INNODB;

CREATE TABLE TblWzskJMUserState(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMUser BIGINT UNSIGNED,
	x1Start INT UNSIGNED,
	ixVState INT UNSIGNED,
	INDEX (refWzskMUser),
	INDEX (x1Start)
) ENGINE = INNODB;

CREATE TABLE TblWzskMFile(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWzskCFile BIGINT UNSIGNED,
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	osrefKContent VARCHAR(50),
	Archived INT UNSIGNED,
	Filename VARCHAR(50),
	Archivename VARCHAR(30),
	srefKMimetype VARCHAR(50),
	Size SMALLINT UNSIGNED,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refWzskCFile),
	INDEX (refIxVTbl),
	INDEX (refUref),
	INDEX (Filename)
) ENGINE = INNODB;

CREATE TABLE TblWzskMObject(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMObjgroup BIGINT UNSIGNED,
	Title VARCHAR(100),
	Comment TEXT,
	INDEX (refWzskMObjgroup),
	INDEX (Title)
) ENGINE = INNODB;

CREATE TABLE TblWzskMObjgroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	supRefWzskMObjgroup BIGINT UNSIGNED,
	sref VARCHAR(50),
	refJTitle BIGINT UNSIGNED,
	Title VARCHAR(100),
	Comment TEXT,
	INDEX (supRefWzskMObjgroup),
	INDEX (sref),
	INDEX (Title)
) ENGINE = INNODB;

CREATE TABLE TblWzskMPerson(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	ixWDerivate INT UNSIGNED,
	ixVSex INT UNSIGNED,
	Title VARCHAR(30),
	Firstname VARCHAR(30),
	refJLastname BIGINT UNSIGNED,
	Lastname VARCHAR(50),
	telRefADetail BIGINT UNSIGNED,
	telVal VARCHAR(192),
	emlRefADetail BIGINT UNSIGNED,
	emlVal VARCHAR(192),
	Salutation VARCHAR(100),
	INDEX (grp),
	INDEX (own),
	INDEX (ixWDerivate),
	INDEX (Lastname)
) ENGINE = INNODB;

CREATE TABLE TblWzskMSession(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMUser BIGINT UNSIGNED,
	start INT UNSIGNED,
	stop INT UNSIGNED,
	Ip VARCHAR(30),
	INDEX (refWzskMUser),
	INDEX (start)
) ENGINE = INNODB;

CREATE TABLE TblWzskMShot(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMSession BIGINT UNSIGNED,
	refWzskMObject BIGINT UNSIGNED,
	start INT UNSIGNED,
	Comment TEXT,
	INDEX (refWzskMSession),
	INDEX (refWzskMObject),
	INDEX (start)
) ENGINE = INNODB;

CREATE TABLE TblWzskMUser(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refRUsergroup BIGINT UNSIGNED,
	refWzskMUsergroup BIGINT UNSIGNED,
	refWzskMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refJState BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixWzskVLocale INT UNSIGNED,
	ixWzskVUserlevel INT UNSIGNED,
	Password VARCHAR(30),
	Fullkey TEXT,
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (refWzskMUsergroup),
	INDEX (refWzskMPerson),
	INDEX (sref),
	INDEX (ixVState)
) ENGINE = INNODB;

CREATE TABLE TblWzskMUsergroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	sref VARCHAR(50),
	Comment TEXT,
	INDEX (grp),
	INDEX (own),
	INDEX (sref)
) ENGINE = INNODB;

CREATE TABLE TblWzskRMUsergroupUniversal(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMUsergroup BIGINT UNSIGNED,
	unvIxWzskVMaintable INT UNSIGNED,
	unvUref BIGINT UNSIGNED,
	ixWzskVRecaccess INT UNSIGNED,
	INDEX (refWzskMUsergroup),
	INDEX (unvIxWzskVMaintable),
	INDEX (unvUref)
) ENGINE = INNODB;

CREATE TABLE TblWzskRMUserMUsergroup(
	ref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	refWzskMUser BIGINT UNSIGNED,
	refWzskMUsergroup BIGINT UNSIGNED,
	ixWzskVUserlevel INT UNSIGNED,
	INDEX (refWzskMUser),
	INDEX (refWzskMUsergroup)
) ENGINE = INNODB;

CREATE TABLE TblWzskQFilList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	Filename VARCHAR(50),
	refIxVTbl INT UNSIGNED,
	refUref BIGINT UNSIGNED,
	osrefKContent VARCHAR(50),
	srefKMimetype VARCHAR(50),
	Size SMALLINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQObjList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	Title VARCHAR(100),
	refWzskMObjgroup BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQObjRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQOgr1NObject(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQOgr1NShot(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQOgrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	sref VARCHAR(50),
	Title VARCHAR(100),
	supRefWzskMObjgroup BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQOgrSup1NObjgroup(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQPreselect(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref)
) ENGINE = INNODB;

CREATE TABLE TblWzskQPrsADetail(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKType VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQPrsList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	Title VARCHAR(30),
	Firstname VARCHAR(30),
	Lastname VARCHAR(50),
	ixVSex INT UNSIGNED,
	telVal VARCHAR(192),
	emlVal VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQSelect(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ix INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (ix)
) ENGINE = INNODB;

CREATE TABLE TblWzskQSes1NShot(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQSesList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refWzskMUser BIGINT UNSIGNED,
	start INT UNSIGNED,
	stop INT UNSIGNED,
	Ip VARCHAR(30),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQShtAPar(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1SrefKKey VARCHAR(50),
	Val VARCHAR(192),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQShtList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	refWzskMSession BIGINT UNSIGNED,
	refWzskMObject BIGINT UNSIGNED,
	start INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQShtRef1NFile(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQUsgAAccess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1IxWzskVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWzskWAccess INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQUsgList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	sref VARCHAR(50),
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQUsgMNUser(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixWzskVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQUsr1NSession(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQUsrAAccess(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	x1IxWzskVFeatgroup INT UNSIGNED,
	x2FeaSrefUix VARCHAR(50),
	ixWzskWAccess INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQUsrList(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	ref BIGINT UNSIGNED,
	grp BIGINT UNSIGNED,
	own BIGINT UNSIGNED,
	refWzskMPerson BIGINT UNSIGNED,
	sref VARCHAR(50),
	refWzskMUsergroup BIGINT UNSIGNED,
	ixVState INT UNSIGNED,
	ixWzskVLocale INT UNSIGNED,
	ixWzskVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

CREATE TABLE TblWzskQUsrMNUsergroup(
	qref BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	jref BIGINT UNSIGNED,
	jnum INT UNSIGNED,
	mref BIGINT UNSIGNED,
	ref BIGINT UNSIGNED,
	ixWzskVUserlevel INT UNSIGNED,
	INDEX (jref),
	INDEX (jnum)
) ENGINE = INNODB;

