/**
  * \file VecWzskVDpch.java
  * vector VecWzskVDpch
  * \author Catherine Johnson
  * \date created: 23 Jul 2020
  * \date modified: 23 Jul 2020
  */

package apiwzsk;

public class VecWzskVDpch {

	public static final int DPCHENGDLGWZSKFILDOWNLOADDATA = 1;
	public static final int DPCHENGDLGWZSKNAVLOAINIDATA = 2;
	public static final int DPCHENGDLGWZSKOBJNEWDATA = 3;
	public static final int DPCHENGDLGWZSKOGRNEWDATA = 4;
	public static final int DPCHENGDLGWZSKSCFCAMERAMATDATA = 5;
	public static final int DPCHENGDLGWZSKSCFLASERPOSDATA = 6;
	public static final int DPCHENGDLGWZSKSCFTTABLECOORDDATA = 7;
	public static final int DPCHENGM2MSESSWZSKDATA = 8;
	public static final int DPCHENGROOTWZSKDATA = 9;
	public static final int DPCHENGSESSWZSKDATA = 10;
	public static final int DPCHENGWZSKACK = 11;
	public static final int DPCHENGWZSKALERT = 12;
	public static final int DPCHENGWZSKCONFIRM = 13;
	public static final int DPCHENGWZSKFILDATA = 14;
	public static final int DPCHENGWZSKFILDETAILDATA = 15;
	public static final int DPCHENGWZSKFILHEADBARDATA = 16;
	public static final int DPCHENGWZSKFILLISTDATA = 17;
	public static final int DPCHENGWZSKFILRECDATA = 18;
	public static final int DPCHENGWZSKLIV2DVIEWALIGN = 19;
	public static final int DPCHENGWZSKLIV2DVIEWDATA = 20;
	public static final int DPCHENGWZSKLIV2DVIEWLIVE = 21;
	public static final int DPCHENGWZSKLIV3DVIEWDATA = 22;
	public static final int DPCHENGWZSKLIV3DVIEWLIVE = 23;
	public static final int DPCHENGWZSKLIVDATA = 24;
	public static final int DPCHENGWZSKLIVHEADBARDATA = 25;
	public static final int DPCHENGWZSKLLVCAMERADATA = 26;
	public static final int DPCHENGWZSKLLVCAMERALIVE = 27;
	public static final int DPCHENGWZSKLLVDATA = 28;
	public static final int DPCHENGWZSKLLVHEADBARDATA = 29;
	public static final int DPCHENGWZSKLLVLASERDATA = 30;
	public static final int DPCHENGWZSKLLVTERMDATA = 31;
	public static final int DPCHENGWZSKLLVTTABLEDATA = 32;
	public static final int DPCHENGWZSKNAVADMINDATA = 33;
	public static final int DPCHENGWZSKNAVDATA = 34;
	public static final int DPCHENGWZSKNAVGALERYDATA = 35;
	public static final int DPCHENGWZSKNAVHEADBARDATA = 36;
	public static final int DPCHENGWZSKNAVOPDATA = 37;
	public static final int DPCHENGWZSKNAVPREDATA = 38;
	public static final int DPCHENGWZSKOBJDATA = 39;
	public static final int DPCHENGWZSKOBJDETAILDATA = 40;
	public static final int DPCHENGWZSKOBJHEADBARDATA = 41;
	public static final int DPCHENGWZSKOBJLISTDATA = 42;
	public static final int DPCHENGWZSKOBJRECDATA = 43;
	public static final int DPCHENGWZSKOBJREF1NFILEDATA = 44;
	public static final int DPCHENGWZSKOGR1NOBJECTDATA = 45;
	public static final int DPCHENGWZSKOGR1NSHOTDATA = 46;
	public static final int DPCHENGWZSKOGRDATA = 47;
	public static final int DPCHENGWZSKOGRDETAILDATA = 48;
	public static final int DPCHENGWZSKOGRHEADBARDATA = 49;
	public static final int DPCHENGWZSKOGRLISTDATA = 50;
	public static final int DPCHENGWZSKOGRRECDATA = 51;
	public static final int DPCHENGWZSKOGRSUP1NOBJGROUPDATA = 52;
	public static final int DPCHENGWZSKPRSADETAILDATA = 53;
	public static final int DPCHENGWZSKPRSDATA = 54;
	public static final int DPCHENGWZSKPRSDETAILDATA = 55;
	public static final int DPCHENGWZSKPRSHEADBARDATA = 56;
	public static final int DPCHENGWZSKPRSLISTDATA = 57;
	public static final int DPCHENGWZSKPRSRECDATA = 58;
	public static final int DPCHENGWZSKSCFCONNDATA = 59;
	public static final int DPCHENGWZSKSCFDATA = 60;
	public static final int DPCHENGWZSKSCFGEOMDATA = 61;
	public static final int DPCHENGWZSKSCFHEADBARDATA = 62;
	public static final int DPCHENGWZSKSES1NSHOTDATA = 63;
	public static final int DPCHENGWZSKSESDATA = 64;
	public static final int DPCHENGWZSKSESDETAILDATA = 65;
	public static final int DPCHENGWZSKSESHEADBARDATA = 66;
	public static final int DPCHENGWZSKSESLISTDATA = 67;
	public static final int DPCHENGWZSKSESRECDATA = 68;
	public static final int DPCHENGWZSKSHTAPARDATA = 69;
	public static final int DPCHENGWZSKSHTDATA = 70;
	public static final int DPCHENGWZSKSHTDETAILDATA = 71;
	public static final int DPCHENGWZSKSHTHEADBARDATA = 72;
	public static final int DPCHENGWZSKSHTLISTDATA = 73;
	public static final int DPCHENGWZSKSHTRECDATA = 74;
	public static final int DPCHENGWZSKSHTREF1NFILEDATA = 75;
	public static final int DPCHENGWZSKSUSPEND = 76;
	public static final int DPCHENGWZSKUSGAACCESSDATA = 77;
	public static final int DPCHENGWZSKUSGDATA = 78;
	public static final int DPCHENGWZSKUSGDETAILDATA = 79;
	public static final int DPCHENGWZSKUSGHEADBARDATA = 80;
	public static final int DPCHENGWZSKUSGLISTDATA = 81;
	public static final int DPCHENGWZSKUSGMNUSERDATA = 82;
	public static final int DPCHENGWZSKUSGRECDATA = 83;
	public static final int DPCHENGWZSKUSR1NSESSIONDATA = 84;
	public static final int DPCHENGWZSKUSRAACCESSDATA = 85;
	public static final int DPCHENGWZSKUSRDATA = 86;
	public static final int DPCHENGWZSKUSRDETAILDATA = 87;
	public static final int DPCHENGWZSKUSRHEADBARDATA = 88;
	public static final int DPCHENGWZSKUSRLISTDATA = 89;
	public static final int DPCHENGWZSKUSRMNUSERGROUPDATA = 90;
	public static final int DPCHENGWZSKUSRRECDATA = 91;
	public static final int DPCHAPPDLGWZSKFILDOWNLOADDO = 92;
	public static final int DPCHAPPDLGWZSKNAVLOAINIDATA = 93;
	public static final int DPCHAPPDLGWZSKNAVLOAINIDO = 94;
	public static final int DPCHAPPDLGWZSKOBJNEWDATA = 95;
	public static final int DPCHAPPDLGWZSKOBJNEWDO = 96;
	public static final int DPCHAPPDLGWZSKOGRNEWDATA = 97;
	public static final int DPCHAPPDLGWZSKOGRNEWDO = 98;
	public static final int DPCHAPPDLGWZSKSCFCAMERAMATDATA = 99;
	public static final int DPCHAPPDLGWZSKSCFCAMERAMATDO = 100;
	public static final int DPCHAPPDLGWZSKSCFLASERPOSDATA = 101;
	public static final int DPCHAPPDLGWZSKSCFLASERPOSDO = 102;
	public static final int DPCHAPPDLGWZSKSCFTTABLECOORDDATA = 103;
	public static final int DPCHAPPDLGWZSKSCFTTABLECOORDDO = 104;
	public static final int DPCHAPPROOTWZSKLOGIN = 105;
	public static final int DPCHAPPWZSKALERT = 106;
	public static final int DPCHAPPWZSKFILDETAILDATA = 107;
	public static final int DPCHAPPWZSKFILDETAILDO = 108;
	public static final int DPCHAPPWZSKFILDO = 109;
	public static final int DPCHAPPWZSKFILLISTDATA = 110;
	public static final int DPCHAPPWZSKFILLISTDO = 111;
	public static final int DPCHAPPWZSKFILRECDO = 112;
	public static final int DPCHAPPWZSKINIT = 113;
	public static final int DPCHAPPWZSKLIV2DVIEWALIGN = 114;
	public static final int DPCHAPPWZSKLIV2DVIEWDATA = 115;
	public static final int DPCHAPPWZSKLIV2DVIEWDO = 116;
	public static final int DPCHAPPWZSKLIV3DVIEWDO = 117;
	public static final int DPCHAPPWZSKLIVDO = 118;
	public static final int DPCHAPPWZSKLLVCAMERADATA = 119;
	public static final int DPCHAPPWZSKLLVCAMERADO = 120;
	public static final int DPCHAPPWZSKLLVDO = 121;
	public static final int DPCHAPPWZSKLLVLASERDATA = 122;
	public static final int DPCHAPPWZSKLLVLASERDO = 123;
	public static final int DPCHAPPWZSKLLVTERMDATA = 124;
	public static final int DPCHAPPWZSKLLVTERMDO = 125;
	public static final int DPCHAPPWZSKLLVTTABLEDATA = 126;
	public static final int DPCHAPPWZSKLLVTTABLEDO = 127;
	public static final int DPCHAPPWZSKNAVADMINDATA = 128;
	public static final int DPCHAPPWZSKNAVADMINDO = 129;
	public static final int DPCHAPPWZSKNAVDO = 130;
	public static final int DPCHAPPWZSKNAVGALERYDATA = 131;
	public static final int DPCHAPPWZSKNAVGALERYDO = 132;
	public static final int DPCHAPPWZSKNAVOPDO = 133;
	public static final int DPCHAPPWZSKNAVPREDO = 134;
	public static final int DPCHAPPWZSKOBJDETAILDATA = 135;
	public static final int DPCHAPPWZSKOBJDETAILDO = 136;
	public static final int DPCHAPPWZSKOBJDO = 137;
	public static final int DPCHAPPWZSKOBJLISTDATA = 138;
	public static final int DPCHAPPWZSKOBJLISTDO = 139;
	public static final int DPCHAPPWZSKOBJRECDO = 140;
	public static final int DPCHAPPWZSKOBJREF1NFILEDATA = 141;
	public static final int DPCHAPPWZSKOBJREF1NFILEDO = 142;
	public static final int DPCHAPPWZSKOGR1NOBJECTDATA = 143;
	public static final int DPCHAPPWZSKOGR1NOBJECTDO = 144;
	public static final int DPCHAPPWZSKOGR1NSHOTDATA = 145;
	public static final int DPCHAPPWZSKOGR1NSHOTDO = 146;
	public static final int DPCHAPPWZSKOGRDETAILDATA = 147;
	public static final int DPCHAPPWZSKOGRDETAILDO = 148;
	public static final int DPCHAPPWZSKOGRDO = 149;
	public static final int DPCHAPPWZSKOGRLISTDATA = 150;
	public static final int DPCHAPPWZSKOGRLISTDO = 151;
	public static final int DPCHAPPWZSKOGRRECDO = 152;
	public static final int DPCHAPPWZSKOGRSUP1NOBJGROUPDATA = 153;
	public static final int DPCHAPPWZSKOGRSUP1NOBJGROUPDO = 154;
	public static final int DPCHAPPWZSKPRSADETAILDATA = 155;
	public static final int DPCHAPPWZSKPRSADETAILDO = 156;
	public static final int DPCHAPPWZSKPRSDETAILDATA = 157;
	public static final int DPCHAPPWZSKPRSDETAILDO = 158;
	public static final int DPCHAPPWZSKPRSDO = 159;
	public static final int DPCHAPPWZSKPRSLISTDATA = 160;
	public static final int DPCHAPPWZSKPRSLISTDO = 161;
	public static final int DPCHAPPWZSKPRSRECDO = 162;
	public static final int DPCHAPPWZSKRESUME = 163;
	public static final int DPCHAPPWZSKSCFCONNDO = 164;
	public static final int DPCHAPPWZSKSCFDO = 165;
	public static final int DPCHAPPWZSKSCFGEOMDO = 166;
	public static final int DPCHAPPWZSKSES1NSHOTDATA = 167;
	public static final int DPCHAPPWZSKSES1NSHOTDO = 168;
	public static final int DPCHAPPWZSKSESDETAILDATA = 169;
	public static final int DPCHAPPWZSKSESDETAILDO = 170;
	public static final int DPCHAPPWZSKSESDO = 171;
	public static final int DPCHAPPWZSKSESLISTDATA = 172;
	public static final int DPCHAPPWZSKSESLISTDO = 173;
	public static final int DPCHAPPWZSKSESRECDO = 174;
	public static final int DPCHAPPWZSKSHTAPARDATA = 175;
	public static final int DPCHAPPWZSKSHTAPARDO = 176;
	public static final int DPCHAPPWZSKSHTDETAILDATA = 177;
	public static final int DPCHAPPWZSKSHTDETAILDO = 178;
	public static final int DPCHAPPWZSKSHTDO = 179;
	public static final int DPCHAPPWZSKSHTLISTDATA = 180;
	public static final int DPCHAPPWZSKSHTLISTDO = 181;
	public static final int DPCHAPPWZSKSHTRECDO = 182;
	public static final int DPCHAPPWZSKSHTREF1NFILEDATA = 183;
	public static final int DPCHAPPWZSKSHTREF1NFILEDO = 184;
	public static final int DPCHAPPWZSKUSGAACCESSDATA = 185;
	public static final int DPCHAPPWZSKUSGAACCESSDO = 186;
	public static final int DPCHAPPWZSKUSGDETAILDATA = 187;
	public static final int DPCHAPPWZSKUSGDETAILDO = 188;
	public static final int DPCHAPPWZSKUSGDO = 189;
	public static final int DPCHAPPWZSKUSGLISTDATA = 190;
	public static final int DPCHAPPWZSKUSGLISTDO = 191;
	public static final int DPCHAPPWZSKUSGMNUSERDATA = 192;
	public static final int DPCHAPPWZSKUSGMNUSERDO = 193;
	public static final int DPCHAPPWZSKUSGRECDO = 194;
	public static final int DPCHAPPWZSKUSR1NSESSIONDATA = 195;
	public static final int DPCHAPPWZSKUSR1NSESSIONDO = 196;
	public static final int DPCHAPPWZSKUSRAACCESSDATA = 197;
	public static final int DPCHAPPWZSKUSRAACCESSDO = 198;
	public static final int DPCHAPPWZSKUSRDETAILDATA = 199;
	public static final int DPCHAPPWZSKUSRDETAILDO = 200;
	public static final int DPCHAPPWZSKUSRDO = 201;
	public static final int DPCHAPPWZSKUSRLISTDATA = 202;
	public static final int DPCHAPPWZSKUSRLISTDO = 203;
	public static final int DPCHAPPWZSKUSRMNUSERGROUPDATA = 204;
	public static final int DPCHAPPWZSKUSRMNUSERGROUPDO = 205;
	public static final int DPCHAPPWZSKUSRRECDO = 206;

	public static int getIx(
				String sref
			) {
		String s = sref.toLowerCase();

		if (s.equals("dpchengdlgwzskfildownloaddata")) return DPCHENGDLGWZSKFILDOWNLOADDATA;
		if (s.equals("dpchengdlgwzsknavloainidata")) return DPCHENGDLGWZSKNAVLOAINIDATA;
		if (s.equals("dpchengdlgwzskobjnewdata")) return DPCHENGDLGWZSKOBJNEWDATA;
		if (s.equals("dpchengdlgwzskogrnewdata")) return DPCHENGDLGWZSKOGRNEWDATA;
		if (s.equals("dpchengdlgwzskscfcameramatdata")) return DPCHENGDLGWZSKSCFCAMERAMATDATA;
		if (s.equals("dpchengdlgwzskscflaserposdata")) return DPCHENGDLGWZSKSCFLASERPOSDATA;
		if (s.equals("dpchengdlgwzskscfttablecoorddata")) return DPCHENGDLGWZSKSCFTTABLECOORDDATA;
		if (s.equals("dpchengm2msesswzskdata")) return DPCHENGM2MSESSWZSKDATA;
		if (s.equals("dpchengrootwzskdata")) return DPCHENGROOTWZSKDATA;
		if (s.equals("dpchengsesswzskdata")) return DPCHENGSESSWZSKDATA;
		if (s.equals("dpchengwzskack")) return DPCHENGWZSKACK;
		if (s.equals("dpchengwzskalert")) return DPCHENGWZSKALERT;
		if (s.equals("dpchengwzskconfirm")) return DPCHENGWZSKCONFIRM;
		if (s.equals("dpchengwzskfildata")) return DPCHENGWZSKFILDATA;
		if (s.equals("dpchengwzskfildetaildata")) return DPCHENGWZSKFILDETAILDATA;
		if (s.equals("dpchengwzskfilheadbardata")) return DPCHENGWZSKFILHEADBARDATA;
		if (s.equals("dpchengwzskfillistdata")) return DPCHENGWZSKFILLISTDATA;
		if (s.equals("dpchengwzskfilrecdata")) return DPCHENGWZSKFILRECDATA;
		if (s.equals("dpchengwzskliv2dviewalign")) return DPCHENGWZSKLIV2DVIEWALIGN;
		if (s.equals("dpchengwzskliv2dviewdata")) return DPCHENGWZSKLIV2DVIEWDATA;
		if (s.equals("dpchengwzskliv2dviewlive")) return DPCHENGWZSKLIV2DVIEWLIVE;
		if (s.equals("dpchengwzskliv3dviewdata")) return DPCHENGWZSKLIV3DVIEWDATA;
		if (s.equals("dpchengwzskliv3dviewlive")) return DPCHENGWZSKLIV3DVIEWLIVE;
		if (s.equals("dpchengwzsklivdata")) return DPCHENGWZSKLIVDATA;
		if (s.equals("dpchengwzsklivheadbardata")) return DPCHENGWZSKLIVHEADBARDATA;
		if (s.equals("dpchengwzskllvcameradata")) return DPCHENGWZSKLLVCAMERADATA;
		if (s.equals("dpchengwzskllvcameralive")) return DPCHENGWZSKLLVCAMERALIVE;
		if (s.equals("dpchengwzskllvdata")) return DPCHENGWZSKLLVDATA;
		if (s.equals("dpchengwzskllvheadbardata")) return DPCHENGWZSKLLVHEADBARDATA;
		if (s.equals("dpchengwzskllvlaserdata")) return DPCHENGWZSKLLVLASERDATA;
		if (s.equals("dpchengwzskllvtermdata")) return DPCHENGWZSKLLVTERMDATA;
		if (s.equals("dpchengwzskllvttabledata")) return DPCHENGWZSKLLVTTABLEDATA;
		if (s.equals("dpchengwzsknavadmindata")) return DPCHENGWZSKNAVADMINDATA;
		if (s.equals("dpchengwzsknavdata")) return DPCHENGWZSKNAVDATA;
		if (s.equals("dpchengwzsknavgalerydata")) return DPCHENGWZSKNAVGALERYDATA;
		if (s.equals("dpchengwzsknavheadbardata")) return DPCHENGWZSKNAVHEADBARDATA;
		if (s.equals("dpchengwzsknavopdata")) return DPCHENGWZSKNAVOPDATA;
		if (s.equals("dpchengwzsknavpredata")) return DPCHENGWZSKNAVPREDATA;
		if (s.equals("dpchengwzskobjdata")) return DPCHENGWZSKOBJDATA;
		if (s.equals("dpchengwzskobjdetaildata")) return DPCHENGWZSKOBJDETAILDATA;
		if (s.equals("dpchengwzskobjheadbardata")) return DPCHENGWZSKOBJHEADBARDATA;
		if (s.equals("dpchengwzskobjlistdata")) return DPCHENGWZSKOBJLISTDATA;
		if (s.equals("dpchengwzskobjrecdata")) return DPCHENGWZSKOBJRECDATA;
		if (s.equals("dpchengwzskobjref1nfiledata")) return DPCHENGWZSKOBJREF1NFILEDATA;
		if (s.equals("dpchengwzskogr1nobjectdata")) return DPCHENGWZSKOGR1NOBJECTDATA;
		if (s.equals("dpchengwzskogr1nshotdata")) return DPCHENGWZSKOGR1NSHOTDATA;
		if (s.equals("dpchengwzskogrdata")) return DPCHENGWZSKOGRDATA;
		if (s.equals("dpchengwzskogrdetaildata")) return DPCHENGWZSKOGRDETAILDATA;
		if (s.equals("dpchengwzskogrheadbardata")) return DPCHENGWZSKOGRHEADBARDATA;
		if (s.equals("dpchengwzskogrlistdata")) return DPCHENGWZSKOGRLISTDATA;
		if (s.equals("dpchengwzskogrrecdata")) return DPCHENGWZSKOGRRECDATA;
		if (s.equals("dpchengwzskogrsup1nobjgroupdata")) return DPCHENGWZSKOGRSUP1NOBJGROUPDATA;
		if (s.equals("dpchengwzskprsadetaildata")) return DPCHENGWZSKPRSADETAILDATA;
		if (s.equals("dpchengwzskprsdata")) return DPCHENGWZSKPRSDATA;
		if (s.equals("dpchengwzskprsdetaildata")) return DPCHENGWZSKPRSDETAILDATA;
		if (s.equals("dpchengwzskprsheadbardata")) return DPCHENGWZSKPRSHEADBARDATA;
		if (s.equals("dpchengwzskprslistdata")) return DPCHENGWZSKPRSLISTDATA;
		if (s.equals("dpchengwzskprsrecdata")) return DPCHENGWZSKPRSRECDATA;
		if (s.equals("dpchengwzskscfconndata")) return DPCHENGWZSKSCFCONNDATA;
		if (s.equals("dpchengwzskscfdata")) return DPCHENGWZSKSCFDATA;
		if (s.equals("dpchengwzskscfgeomdata")) return DPCHENGWZSKSCFGEOMDATA;
		if (s.equals("dpchengwzskscfheadbardata")) return DPCHENGWZSKSCFHEADBARDATA;
		if (s.equals("dpchengwzskses1nshotdata")) return DPCHENGWZSKSES1NSHOTDATA;
		if (s.equals("dpchengwzsksesdata")) return DPCHENGWZSKSESDATA;
		if (s.equals("dpchengwzsksesdetaildata")) return DPCHENGWZSKSESDETAILDATA;
		if (s.equals("dpchengwzsksesheadbardata")) return DPCHENGWZSKSESHEADBARDATA;
		if (s.equals("dpchengwzskseslistdata")) return DPCHENGWZSKSESLISTDATA;
		if (s.equals("dpchengwzsksesrecdata")) return DPCHENGWZSKSESRECDATA;
		if (s.equals("dpchengwzskshtapardata")) return DPCHENGWZSKSHTAPARDATA;
		if (s.equals("dpchengwzskshtdata")) return DPCHENGWZSKSHTDATA;
		if (s.equals("dpchengwzskshtdetaildata")) return DPCHENGWZSKSHTDETAILDATA;
		if (s.equals("dpchengwzskshtheadbardata")) return DPCHENGWZSKSHTHEADBARDATA;
		if (s.equals("dpchengwzskshtlistdata")) return DPCHENGWZSKSHTLISTDATA;
		if (s.equals("dpchengwzskshtrecdata")) return DPCHENGWZSKSHTRECDATA;
		if (s.equals("dpchengwzskshtref1nfiledata")) return DPCHENGWZSKSHTREF1NFILEDATA;
		if (s.equals("dpchengwzsksuspend")) return DPCHENGWZSKSUSPEND;
		if (s.equals("dpchengwzskusgaaccessdata")) return DPCHENGWZSKUSGAACCESSDATA;
		if (s.equals("dpchengwzskusgdata")) return DPCHENGWZSKUSGDATA;
		if (s.equals("dpchengwzskusgdetaildata")) return DPCHENGWZSKUSGDETAILDATA;
		if (s.equals("dpchengwzskusgheadbardata")) return DPCHENGWZSKUSGHEADBARDATA;
		if (s.equals("dpchengwzskusglistdata")) return DPCHENGWZSKUSGLISTDATA;
		if (s.equals("dpchengwzskusgmnuserdata")) return DPCHENGWZSKUSGMNUSERDATA;
		if (s.equals("dpchengwzskusgrecdata")) return DPCHENGWZSKUSGRECDATA;
		if (s.equals("dpchengwzskusr1nsessiondata")) return DPCHENGWZSKUSR1NSESSIONDATA;
		if (s.equals("dpchengwzskusraaccessdata")) return DPCHENGWZSKUSRAACCESSDATA;
		if (s.equals("dpchengwzskusrdata")) return DPCHENGWZSKUSRDATA;
		if (s.equals("dpchengwzskusrdetaildata")) return DPCHENGWZSKUSRDETAILDATA;
		if (s.equals("dpchengwzskusrheadbardata")) return DPCHENGWZSKUSRHEADBARDATA;
		if (s.equals("dpchengwzskusrlistdata")) return DPCHENGWZSKUSRLISTDATA;
		if (s.equals("dpchengwzskusrmnusergroupdata")) return DPCHENGWZSKUSRMNUSERGROUPDATA;
		if (s.equals("dpchengwzskusrrecdata")) return DPCHENGWZSKUSRRECDATA;
		if (s.equals("dpchappdlgwzskfildownloaddo")) return DPCHAPPDLGWZSKFILDOWNLOADDO;
		if (s.equals("dpchappdlgwzsknavloainidata")) return DPCHAPPDLGWZSKNAVLOAINIDATA;
		if (s.equals("dpchappdlgwzsknavloainido")) return DPCHAPPDLGWZSKNAVLOAINIDO;
		if (s.equals("dpchappdlgwzskobjnewdata")) return DPCHAPPDLGWZSKOBJNEWDATA;
		if (s.equals("dpchappdlgwzskobjnewdo")) return DPCHAPPDLGWZSKOBJNEWDO;
		if (s.equals("dpchappdlgwzskogrnewdata")) return DPCHAPPDLGWZSKOGRNEWDATA;
		if (s.equals("dpchappdlgwzskogrnewdo")) return DPCHAPPDLGWZSKOGRNEWDO;
		if (s.equals("dpchappdlgwzskscfcameramatdata")) return DPCHAPPDLGWZSKSCFCAMERAMATDATA;
		if (s.equals("dpchappdlgwzskscfcameramatdo")) return DPCHAPPDLGWZSKSCFCAMERAMATDO;
		if (s.equals("dpchappdlgwzskscflaserposdata")) return DPCHAPPDLGWZSKSCFLASERPOSDATA;
		if (s.equals("dpchappdlgwzskscflaserposdo")) return DPCHAPPDLGWZSKSCFLASERPOSDO;
		if (s.equals("dpchappdlgwzskscfttablecoorddata")) return DPCHAPPDLGWZSKSCFTTABLECOORDDATA;
		if (s.equals("dpchappdlgwzskscfttablecoorddo")) return DPCHAPPDLGWZSKSCFTTABLECOORDDO;
		if (s.equals("dpchapprootwzsklogin")) return DPCHAPPROOTWZSKLOGIN;
		if (s.equals("dpchappwzskalert")) return DPCHAPPWZSKALERT;
		if (s.equals("dpchappwzskfildetaildata")) return DPCHAPPWZSKFILDETAILDATA;
		if (s.equals("dpchappwzskfildetaildo")) return DPCHAPPWZSKFILDETAILDO;
		if (s.equals("dpchappwzskfildo")) return DPCHAPPWZSKFILDO;
		if (s.equals("dpchappwzskfillistdata")) return DPCHAPPWZSKFILLISTDATA;
		if (s.equals("dpchappwzskfillistdo")) return DPCHAPPWZSKFILLISTDO;
		if (s.equals("dpchappwzskfilrecdo")) return DPCHAPPWZSKFILRECDO;
		if (s.equals("dpchappwzskinit")) return DPCHAPPWZSKINIT;
		if (s.equals("dpchappwzskliv2dviewalign")) return DPCHAPPWZSKLIV2DVIEWALIGN;
		if (s.equals("dpchappwzskliv2dviewdata")) return DPCHAPPWZSKLIV2DVIEWDATA;
		if (s.equals("dpchappwzskliv2dviewdo")) return DPCHAPPWZSKLIV2DVIEWDO;
		if (s.equals("dpchappwzskliv3dviewdo")) return DPCHAPPWZSKLIV3DVIEWDO;
		if (s.equals("dpchappwzsklivdo")) return DPCHAPPWZSKLIVDO;
		if (s.equals("dpchappwzskllvcameradata")) return DPCHAPPWZSKLLVCAMERADATA;
		if (s.equals("dpchappwzskllvcamerado")) return DPCHAPPWZSKLLVCAMERADO;
		if (s.equals("dpchappwzskllvdo")) return DPCHAPPWZSKLLVDO;
		if (s.equals("dpchappwzskllvlaserdata")) return DPCHAPPWZSKLLVLASERDATA;
		if (s.equals("dpchappwzskllvlaserdo")) return DPCHAPPWZSKLLVLASERDO;
		if (s.equals("dpchappwzskllvtermdata")) return DPCHAPPWZSKLLVTERMDATA;
		if (s.equals("dpchappwzskllvtermdo")) return DPCHAPPWZSKLLVTERMDO;
		if (s.equals("dpchappwzskllvttabledata")) return DPCHAPPWZSKLLVTTABLEDATA;
		if (s.equals("dpchappwzskllvttabledo")) return DPCHAPPWZSKLLVTTABLEDO;
		if (s.equals("dpchappwzsknavadmindata")) return DPCHAPPWZSKNAVADMINDATA;
		if (s.equals("dpchappwzsknavadmindo")) return DPCHAPPWZSKNAVADMINDO;
		if (s.equals("dpchappwzsknavdo")) return DPCHAPPWZSKNAVDO;
		if (s.equals("dpchappwzsknavgalerydata")) return DPCHAPPWZSKNAVGALERYDATA;
		if (s.equals("dpchappwzsknavgalerydo")) return DPCHAPPWZSKNAVGALERYDO;
		if (s.equals("dpchappwzsknavopdo")) return DPCHAPPWZSKNAVOPDO;
		if (s.equals("dpchappwzsknavpredo")) return DPCHAPPWZSKNAVPREDO;
		if (s.equals("dpchappwzskobjdetaildata")) return DPCHAPPWZSKOBJDETAILDATA;
		if (s.equals("dpchappwzskobjdetaildo")) return DPCHAPPWZSKOBJDETAILDO;
		if (s.equals("dpchappwzskobjdo")) return DPCHAPPWZSKOBJDO;
		if (s.equals("dpchappwzskobjlistdata")) return DPCHAPPWZSKOBJLISTDATA;
		if (s.equals("dpchappwzskobjlistdo")) return DPCHAPPWZSKOBJLISTDO;
		if (s.equals("dpchappwzskobjrecdo")) return DPCHAPPWZSKOBJRECDO;
		if (s.equals("dpchappwzskobjref1nfiledata")) return DPCHAPPWZSKOBJREF1NFILEDATA;
		if (s.equals("dpchappwzskobjref1nfiledo")) return DPCHAPPWZSKOBJREF1NFILEDO;
		if (s.equals("dpchappwzskogr1nobjectdata")) return DPCHAPPWZSKOGR1NOBJECTDATA;
		if (s.equals("dpchappwzskogr1nobjectdo")) return DPCHAPPWZSKOGR1NOBJECTDO;
		if (s.equals("dpchappwzskogr1nshotdata")) return DPCHAPPWZSKOGR1NSHOTDATA;
		if (s.equals("dpchappwzskogr1nshotdo")) return DPCHAPPWZSKOGR1NSHOTDO;
		if (s.equals("dpchappwzskogrdetaildata")) return DPCHAPPWZSKOGRDETAILDATA;
		if (s.equals("dpchappwzskogrdetaildo")) return DPCHAPPWZSKOGRDETAILDO;
		if (s.equals("dpchappwzskogrdo")) return DPCHAPPWZSKOGRDO;
		if (s.equals("dpchappwzskogrlistdata")) return DPCHAPPWZSKOGRLISTDATA;
		if (s.equals("dpchappwzskogrlistdo")) return DPCHAPPWZSKOGRLISTDO;
		if (s.equals("dpchappwzskogrrecdo")) return DPCHAPPWZSKOGRRECDO;
		if (s.equals("dpchappwzskogrsup1nobjgroupdata")) return DPCHAPPWZSKOGRSUP1NOBJGROUPDATA;
		if (s.equals("dpchappwzskogrsup1nobjgroupdo")) return DPCHAPPWZSKOGRSUP1NOBJGROUPDO;
		if (s.equals("dpchappwzskprsadetaildata")) return DPCHAPPWZSKPRSADETAILDATA;
		if (s.equals("dpchappwzskprsadetaildo")) return DPCHAPPWZSKPRSADETAILDO;
		if (s.equals("dpchappwzskprsdetaildata")) return DPCHAPPWZSKPRSDETAILDATA;
		if (s.equals("dpchappwzskprsdetaildo")) return DPCHAPPWZSKPRSDETAILDO;
		if (s.equals("dpchappwzskprsdo")) return DPCHAPPWZSKPRSDO;
		if (s.equals("dpchappwzskprslistdata")) return DPCHAPPWZSKPRSLISTDATA;
		if (s.equals("dpchappwzskprslistdo")) return DPCHAPPWZSKPRSLISTDO;
		if (s.equals("dpchappwzskprsrecdo")) return DPCHAPPWZSKPRSRECDO;
		if (s.equals("dpchappwzskresume")) return DPCHAPPWZSKRESUME;
		if (s.equals("dpchappwzskscfconndo")) return DPCHAPPWZSKSCFCONNDO;
		if (s.equals("dpchappwzskscfdo")) return DPCHAPPWZSKSCFDO;
		if (s.equals("dpchappwzskscfgeomdo")) return DPCHAPPWZSKSCFGEOMDO;
		if (s.equals("dpchappwzskses1nshotdata")) return DPCHAPPWZSKSES1NSHOTDATA;
		if (s.equals("dpchappwzskses1nshotdo")) return DPCHAPPWZSKSES1NSHOTDO;
		if (s.equals("dpchappwzsksesdetaildata")) return DPCHAPPWZSKSESDETAILDATA;
		if (s.equals("dpchappwzsksesdetaildo")) return DPCHAPPWZSKSESDETAILDO;
		if (s.equals("dpchappwzsksesdo")) return DPCHAPPWZSKSESDO;
		if (s.equals("dpchappwzskseslistdata")) return DPCHAPPWZSKSESLISTDATA;
		if (s.equals("dpchappwzskseslistdo")) return DPCHAPPWZSKSESLISTDO;
		if (s.equals("dpchappwzsksesrecdo")) return DPCHAPPWZSKSESRECDO;
		if (s.equals("dpchappwzskshtapardata")) return DPCHAPPWZSKSHTAPARDATA;
		if (s.equals("dpchappwzskshtapardo")) return DPCHAPPWZSKSHTAPARDO;
		if (s.equals("dpchappwzskshtdetaildata")) return DPCHAPPWZSKSHTDETAILDATA;
		if (s.equals("dpchappwzskshtdetaildo")) return DPCHAPPWZSKSHTDETAILDO;
		if (s.equals("dpchappwzskshtdo")) return DPCHAPPWZSKSHTDO;
		if (s.equals("dpchappwzskshtlistdata")) return DPCHAPPWZSKSHTLISTDATA;
		if (s.equals("dpchappwzskshtlistdo")) return DPCHAPPWZSKSHTLISTDO;
		if (s.equals("dpchappwzskshtrecdo")) return DPCHAPPWZSKSHTRECDO;
		if (s.equals("dpchappwzskshtref1nfiledata")) return DPCHAPPWZSKSHTREF1NFILEDATA;
		if (s.equals("dpchappwzskshtref1nfiledo")) return DPCHAPPWZSKSHTREF1NFILEDO;
		if (s.equals("dpchappwzskusgaaccessdata")) return DPCHAPPWZSKUSGAACCESSDATA;
		if (s.equals("dpchappwzskusgaaccessdo")) return DPCHAPPWZSKUSGAACCESSDO;
		if (s.equals("dpchappwzskusgdetaildata")) return DPCHAPPWZSKUSGDETAILDATA;
		if (s.equals("dpchappwzskusgdetaildo")) return DPCHAPPWZSKUSGDETAILDO;
		if (s.equals("dpchappwzskusgdo")) return DPCHAPPWZSKUSGDO;
		if (s.equals("dpchappwzskusglistdata")) return DPCHAPPWZSKUSGLISTDATA;
		if (s.equals("dpchappwzskusglistdo")) return DPCHAPPWZSKUSGLISTDO;
		if (s.equals("dpchappwzskusgmnuserdata")) return DPCHAPPWZSKUSGMNUSERDATA;
		if (s.equals("dpchappwzskusgmnuserdo")) return DPCHAPPWZSKUSGMNUSERDO;
		if (s.equals("dpchappwzskusgrecdo")) return DPCHAPPWZSKUSGRECDO;
		if (s.equals("dpchappwzskusr1nsessiondata")) return DPCHAPPWZSKUSR1NSESSIONDATA;
		if (s.equals("dpchappwzskusr1nsessiondo")) return DPCHAPPWZSKUSR1NSESSIONDO;
		if (s.equals("dpchappwzskusraaccessdata")) return DPCHAPPWZSKUSRAACCESSDATA;
		if (s.equals("dpchappwzskusraaccessdo")) return DPCHAPPWZSKUSRAACCESSDO;
		if (s.equals("dpchappwzskusrdetaildata")) return DPCHAPPWZSKUSRDETAILDATA;
		if (s.equals("dpchappwzskusrdetaildo")) return DPCHAPPWZSKUSRDETAILDO;
		if (s.equals("dpchappwzskusrdo")) return DPCHAPPWZSKUSRDO;
		if (s.equals("dpchappwzskusrlistdata")) return DPCHAPPWZSKUSRLISTDATA;
		if (s.equals("dpchappwzskusrlistdo")) return DPCHAPPWZSKUSRLISTDO;
		if (s.equals("dpchappwzskusrmnusergroupdata")) return DPCHAPPWZSKUSRMNUSERGROUPDATA;
		if (s.equals("dpchappwzskusrmnusergroupdo")) return DPCHAPPWZSKUSRMNUSERGROUPDO;
		if (s.equals("dpchappwzskusrrecdo")) return DPCHAPPWZSKUSRRECDO;

		return 0;
	};
	
	public static String getSref(
				int ix
			) {
		if (ix == DPCHENGDLGWZSKFILDOWNLOADDATA) return("DpchEngDlgWzskFilDownloadData");
		if (ix == DPCHENGDLGWZSKNAVLOAINIDATA) return("DpchEngDlgWzskNavLoainiData");
		if (ix == DPCHENGDLGWZSKOBJNEWDATA) return("DpchEngDlgWzskObjNewData");
		if (ix == DPCHENGDLGWZSKOGRNEWDATA) return("DpchEngDlgWzskOgrNewData");
		if (ix == DPCHENGDLGWZSKSCFCAMERAMATDATA) return("DpchEngDlgWzskScfCameramatData");
		if (ix == DPCHENGDLGWZSKSCFLASERPOSDATA) return("DpchEngDlgWzskScfLaserposData");
		if (ix == DPCHENGDLGWZSKSCFTTABLECOORDDATA) return("DpchEngDlgWzskScfTtablecoordData");
		if (ix == DPCHENGM2MSESSWZSKDATA) return("DpchEngM2msessWzskData");
		if (ix == DPCHENGROOTWZSKDATA) return("DpchEngRootWzskData");
		if (ix == DPCHENGSESSWZSKDATA) return("DpchEngSessWzskData");
		if (ix == DPCHENGWZSKACK) return("DpchEngWzskAck");
		if (ix == DPCHENGWZSKALERT) return("DpchEngWzskAlert");
		if (ix == DPCHENGWZSKCONFIRM) return("DpchEngWzskConfirm");
		if (ix == DPCHENGWZSKFILDATA) return("DpchEngWzskFilData");
		if (ix == DPCHENGWZSKFILDETAILDATA) return("DpchEngWzskFilDetailData");
		if (ix == DPCHENGWZSKFILHEADBARDATA) return("DpchEngWzskFilHeadbarData");
		if (ix == DPCHENGWZSKFILLISTDATA) return("DpchEngWzskFilListData");
		if (ix == DPCHENGWZSKFILRECDATA) return("DpchEngWzskFilRecData");
		if (ix == DPCHENGWZSKLIV2DVIEWALIGN) return("DpchEngWzskLiv2DViewAlign");
		if (ix == DPCHENGWZSKLIV2DVIEWDATA) return("DpchEngWzskLiv2DViewData");
		if (ix == DPCHENGWZSKLIV2DVIEWLIVE) return("DpchEngWzskLiv2DViewLive");
		if (ix == DPCHENGWZSKLIV3DVIEWDATA) return("DpchEngWzskLiv3DViewData");
		if (ix == DPCHENGWZSKLIV3DVIEWLIVE) return("DpchEngWzskLiv3DViewLive");
		if (ix == DPCHENGWZSKLIVDATA) return("DpchEngWzskLivData");
		if (ix == DPCHENGWZSKLIVHEADBARDATA) return("DpchEngWzskLivHeadbarData");
		if (ix == DPCHENGWZSKLLVCAMERADATA) return("DpchEngWzskLlvCameraData");
		if (ix == DPCHENGWZSKLLVCAMERALIVE) return("DpchEngWzskLlvCameraLive");
		if (ix == DPCHENGWZSKLLVDATA) return("DpchEngWzskLlvData");
		if (ix == DPCHENGWZSKLLVHEADBARDATA) return("DpchEngWzskLlvHeadbarData");
		if (ix == DPCHENGWZSKLLVLASERDATA) return("DpchEngWzskLlvLaserData");
		if (ix == DPCHENGWZSKLLVTERMDATA) return("DpchEngWzskLlvTermData");
		if (ix == DPCHENGWZSKLLVTTABLEDATA) return("DpchEngWzskLlvTtableData");
		if (ix == DPCHENGWZSKNAVADMINDATA) return("DpchEngWzskNavAdminData");
		if (ix == DPCHENGWZSKNAVDATA) return("DpchEngWzskNavData");
		if (ix == DPCHENGWZSKNAVGALERYDATA) return("DpchEngWzskNavGaleryData");
		if (ix == DPCHENGWZSKNAVHEADBARDATA) return("DpchEngWzskNavHeadbarData");
		if (ix == DPCHENGWZSKNAVOPDATA) return("DpchEngWzskNavOpData");
		if (ix == DPCHENGWZSKNAVPREDATA) return("DpchEngWzskNavPreData");
		if (ix == DPCHENGWZSKOBJDATA) return("DpchEngWzskObjData");
		if (ix == DPCHENGWZSKOBJDETAILDATA) return("DpchEngWzskObjDetailData");
		if (ix == DPCHENGWZSKOBJHEADBARDATA) return("DpchEngWzskObjHeadbarData");
		if (ix == DPCHENGWZSKOBJLISTDATA) return("DpchEngWzskObjListData");
		if (ix == DPCHENGWZSKOBJRECDATA) return("DpchEngWzskObjRecData");
		if (ix == DPCHENGWZSKOBJREF1NFILEDATA) return("DpchEngWzskObjRef1NFileData");
		if (ix == DPCHENGWZSKOGR1NOBJECTDATA) return("DpchEngWzskOgr1NObjectData");
		if (ix == DPCHENGWZSKOGR1NSHOTDATA) return("DpchEngWzskOgr1NShotData");
		if (ix == DPCHENGWZSKOGRDATA) return("DpchEngWzskOgrData");
		if (ix == DPCHENGWZSKOGRDETAILDATA) return("DpchEngWzskOgrDetailData");
		if (ix == DPCHENGWZSKOGRHEADBARDATA) return("DpchEngWzskOgrHeadbarData");
		if (ix == DPCHENGWZSKOGRLISTDATA) return("DpchEngWzskOgrListData");
		if (ix == DPCHENGWZSKOGRRECDATA) return("DpchEngWzskOgrRecData");
		if (ix == DPCHENGWZSKOGRSUP1NOBJGROUPDATA) return("DpchEngWzskOgrSup1NObjgroupData");
		if (ix == DPCHENGWZSKPRSADETAILDATA) return("DpchEngWzskPrsADetailData");
		if (ix == DPCHENGWZSKPRSDATA) return("DpchEngWzskPrsData");
		if (ix == DPCHENGWZSKPRSDETAILDATA) return("DpchEngWzskPrsDetailData");
		if (ix == DPCHENGWZSKPRSHEADBARDATA) return("DpchEngWzskPrsHeadbarData");
		if (ix == DPCHENGWZSKPRSLISTDATA) return("DpchEngWzskPrsListData");
		if (ix == DPCHENGWZSKPRSRECDATA) return("DpchEngWzskPrsRecData");
		if (ix == DPCHENGWZSKSCFCONNDATA) return("DpchEngWzskScfConnData");
		if (ix == DPCHENGWZSKSCFDATA) return("DpchEngWzskScfData");
		if (ix == DPCHENGWZSKSCFGEOMDATA) return("DpchEngWzskScfGeomData");
		if (ix == DPCHENGWZSKSCFHEADBARDATA) return("DpchEngWzskScfHeadbarData");
		if (ix == DPCHENGWZSKSES1NSHOTDATA) return("DpchEngWzskSes1NShotData");
		if (ix == DPCHENGWZSKSESDATA) return("DpchEngWzskSesData");
		if (ix == DPCHENGWZSKSESDETAILDATA) return("DpchEngWzskSesDetailData");
		if (ix == DPCHENGWZSKSESHEADBARDATA) return("DpchEngWzskSesHeadbarData");
		if (ix == DPCHENGWZSKSESLISTDATA) return("DpchEngWzskSesListData");
		if (ix == DPCHENGWZSKSESRECDATA) return("DpchEngWzskSesRecData");
		if (ix == DPCHENGWZSKSHTAPARDATA) return("DpchEngWzskShtAParData");
		if (ix == DPCHENGWZSKSHTDATA) return("DpchEngWzskShtData");
		if (ix == DPCHENGWZSKSHTDETAILDATA) return("DpchEngWzskShtDetailData");
		if (ix == DPCHENGWZSKSHTHEADBARDATA) return("DpchEngWzskShtHeadbarData");
		if (ix == DPCHENGWZSKSHTLISTDATA) return("DpchEngWzskShtListData");
		if (ix == DPCHENGWZSKSHTRECDATA) return("DpchEngWzskShtRecData");
		if (ix == DPCHENGWZSKSHTREF1NFILEDATA) return("DpchEngWzskShtRef1NFileData");
		if (ix == DPCHENGWZSKSUSPEND) return("DpchEngWzskSuspend");
		if (ix == DPCHENGWZSKUSGAACCESSDATA) return("DpchEngWzskUsgAAccessData");
		if (ix == DPCHENGWZSKUSGDATA) return("DpchEngWzskUsgData");
		if (ix == DPCHENGWZSKUSGDETAILDATA) return("DpchEngWzskUsgDetailData");
		if (ix == DPCHENGWZSKUSGHEADBARDATA) return("DpchEngWzskUsgHeadbarData");
		if (ix == DPCHENGWZSKUSGLISTDATA) return("DpchEngWzskUsgListData");
		if (ix == DPCHENGWZSKUSGMNUSERDATA) return("DpchEngWzskUsgMNUserData");
		if (ix == DPCHENGWZSKUSGRECDATA) return("DpchEngWzskUsgRecData");
		if (ix == DPCHENGWZSKUSR1NSESSIONDATA) return("DpchEngWzskUsr1NSessionData");
		if (ix == DPCHENGWZSKUSRAACCESSDATA) return("DpchEngWzskUsrAAccessData");
		if (ix == DPCHENGWZSKUSRDATA) return("DpchEngWzskUsrData");
		if (ix == DPCHENGWZSKUSRDETAILDATA) return("DpchEngWzskUsrDetailData");
		if (ix == DPCHENGWZSKUSRHEADBARDATA) return("DpchEngWzskUsrHeadbarData");
		if (ix == DPCHENGWZSKUSRLISTDATA) return("DpchEngWzskUsrListData");
		if (ix == DPCHENGWZSKUSRMNUSERGROUPDATA) return("DpchEngWzskUsrMNUsergroupData");
		if (ix == DPCHENGWZSKUSRRECDATA) return("DpchEngWzskUsrRecData");
		if (ix == DPCHAPPDLGWZSKFILDOWNLOADDO) return("DpchAppDlgWzskFilDownloadDo");
		if (ix == DPCHAPPDLGWZSKNAVLOAINIDATA) return("DpchAppDlgWzskNavLoainiData");
		if (ix == DPCHAPPDLGWZSKNAVLOAINIDO) return("DpchAppDlgWzskNavLoainiDo");
		if (ix == DPCHAPPDLGWZSKOBJNEWDATA) return("DpchAppDlgWzskObjNewData");
		if (ix == DPCHAPPDLGWZSKOBJNEWDO) return("DpchAppDlgWzskObjNewDo");
		if (ix == DPCHAPPDLGWZSKOGRNEWDATA) return("DpchAppDlgWzskOgrNewData");
		if (ix == DPCHAPPDLGWZSKOGRNEWDO) return("DpchAppDlgWzskOgrNewDo");
		if (ix == DPCHAPPDLGWZSKSCFCAMERAMATDATA) return("DpchAppDlgWzskScfCameramatData");
		if (ix == DPCHAPPDLGWZSKSCFCAMERAMATDO) return("DpchAppDlgWzskScfCameramatDo");
		if (ix == DPCHAPPDLGWZSKSCFLASERPOSDATA) return("DpchAppDlgWzskScfLaserposData");
		if (ix == DPCHAPPDLGWZSKSCFLASERPOSDO) return("DpchAppDlgWzskScfLaserposDo");
		if (ix == DPCHAPPDLGWZSKSCFTTABLECOORDDATA) return("DpchAppDlgWzskScfTtablecoordData");
		if (ix == DPCHAPPDLGWZSKSCFTTABLECOORDDO) return("DpchAppDlgWzskScfTtablecoordDo");
		if (ix == DPCHAPPROOTWZSKLOGIN) return("DpchAppRootWzskLogin");
		if (ix == DPCHAPPWZSKALERT) return("DpchAppWzskAlert");
		if (ix == DPCHAPPWZSKFILDETAILDATA) return("DpchAppWzskFilDetailData");
		if (ix == DPCHAPPWZSKFILDETAILDO) return("DpchAppWzskFilDetailDo");
		if (ix == DPCHAPPWZSKFILDO) return("DpchAppWzskFilDo");
		if (ix == DPCHAPPWZSKFILLISTDATA) return("DpchAppWzskFilListData");
		if (ix == DPCHAPPWZSKFILLISTDO) return("DpchAppWzskFilListDo");
		if (ix == DPCHAPPWZSKFILRECDO) return("DpchAppWzskFilRecDo");
		if (ix == DPCHAPPWZSKINIT) return("DpchAppWzskInit");
		if (ix == DPCHAPPWZSKLIV2DVIEWALIGN) return("DpchAppWzskLiv2DViewAlign");
		if (ix == DPCHAPPWZSKLIV2DVIEWDATA) return("DpchAppWzskLiv2DViewData");
		if (ix == DPCHAPPWZSKLIV2DVIEWDO) return("DpchAppWzskLiv2DViewDo");
		if (ix == DPCHAPPWZSKLIV3DVIEWDO) return("DpchAppWzskLiv3DViewDo");
		if (ix == DPCHAPPWZSKLIVDO) return("DpchAppWzskLivDo");
		if (ix == DPCHAPPWZSKLLVCAMERADATA) return("DpchAppWzskLlvCameraData");
		if (ix == DPCHAPPWZSKLLVCAMERADO) return("DpchAppWzskLlvCameraDo");
		if (ix == DPCHAPPWZSKLLVDO) return("DpchAppWzskLlvDo");
		if (ix == DPCHAPPWZSKLLVLASERDATA) return("DpchAppWzskLlvLaserData");
		if (ix == DPCHAPPWZSKLLVLASERDO) return("DpchAppWzskLlvLaserDo");
		if (ix == DPCHAPPWZSKLLVTERMDATA) return("DpchAppWzskLlvTermData");
		if (ix == DPCHAPPWZSKLLVTERMDO) return("DpchAppWzskLlvTermDo");
		if (ix == DPCHAPPWZSKLLVTTABLEDATA) return("DpchAppWzskLlvTtableData");
		if (ix == DPCHAPPWZSKLLVTTABLEDO) return("DpchAppWzskLlvTtableDo");
		if (ix == DPCHAPPWZSKNAVADMINDATA) return("DpchAppWzskNavAdminData");
		if (ix == DPCHAPPWZSKNAVADMINDO) return("DpchAppWzskNavAdminDo");
		if (ix == DPCHAPPWZSKNAVDO) return("DpchAppWzskNavDo");
		if (ix == DPCHAPPWZSKNAVGALERYDATA) return("DpchAppWzskNavGaleryData");
		if (ix == DPCHAPPWZSKNAVGALERYDO) return("DpchAppWzskNavGaleryDo");
		if (ix == DPCHAPPWZSKNAVOPDO) return("DpchAppWzskNavOpDo");
		if (ix == DPCHAPPWZSKNAVPREDO) return("DpchAppWzskNavPreDo");
		if (ix == DPCHAPPWZSKOBJDETAILDATA) return("DpchAppWzskObjDetailData");
		if (ix == DPCHAPPWZSKOBJDETAILDO) return("DpchAppWzskObjDetailDo");
		if (ix == DPCHAPPWZSKOBJDO) return("DpchAppWzskObjDo");
		if (ix == DPCHAPPWZSKOBJLISTDATA) return("DpchAppWzskObjListData");
		if (ix == DPCHAPPWZSKOBJLISTDO) return("DpchAppWzskObjListDo");
		if (ix == DPCHAPPWZSKOBJRECDO) return("DpchAppWzskObjRecDo");
		if (ix == DPCHAPPWZSKOBJREF1NFILEDATA) return("DpchAppWzskObjRef1NFileData");
		if (ix == DPCHAPPWZSKOBJREF1NFILEDO) return("DpchAppWzskObjRef1NFileDo");
		if (ix == DPCHAPPWZSKOGR1NOBJECTDATA) return("DpchAppWzskOgr1NObjectData");
		if (ix == DPCHAPPWZSKOGR1NOBJECTDO) return("DpchAppWzskOgr1NObjectDo");
		if (ix == DPCHAPPWZSKOGR1NSHOTDATA) return("DpchAppWzskOgr1NShotData");
		if (ix == DPCHAPPWZSKOGR1NSHOTDO) return("DpchAppWzskOgr1NShotDo");
		if (ix == DPCHAPPWZSKOGRDETAILDATA) return("DpchAppWzskOgrDetailData");
		if (ix == DPCHAPPWZSKOGRDETAILDO) return("DpchAppWzskOgrDetailDo");
		if (ix == DPCHAPPWZSKOGRDO) return("DpchAppWzskOgrDo");
		if (ix == DPCHAPPWZSKOGRLISTDATA) return("DpchAppWzskOgrListData");
		if (ix == DPCHAPPWZSKOGRLISTDO) return("DpchAppWzskOgrListDo");
		if (ix == DPCHAPPWZSKOGRRECDO) return("DpchAppWzskOgrRecDo");
		if (ix == DPCHAPPWZSKOGRSUP1NOBJGROUPDATA) return("DpchAppWzskOgrSup1NObjgroupData");
		if (ix == DPCHAPPWZSKOGRSUP1NOBJGROUPDO) return("DpchAppWzskOgrSup1NObjgroupDo");
		if (ix == DPCHAPPWZSKPRSADETAILDATA) return("DpchAppWzskPrsADetailData");
		if (ix == DPCHAPPWZSKPRSADETAILDO) return("DpchAppWzskPrsADetailDo");
		if (ix == DPCHAPPWZSKPRSDETAILDATA) return("DpchAppWzskPrsDetailData");
		if (ix == DPCHAPPWZSKPRSDETAILDO) return("DpchAppWzskPrsDetailDo");
		if (ix == DPCHAPPWZSKPRSDO) return("DpchAppWzskPrsDo");
		if (ix == DPCHAPPWZSKPRSLISTDATA) return("DpchAppWzskPrsListData");
		if (ix == DPCHAPPWZSKPRSLISTDO) return("DpchAppWzskPrsListDo");
		if (ix == DPCHAPPWZSKPRSRECDO) return("DpchAppWzskPrsRecDo");
		if (ix == DPCHAPPWZSKRESUME) return("DpchAppWzskResume");
		if (ix == DPCHAPPWZSKSCFCONNDO) return("DpchAppWzskScfConnDo");
		if (ix == DPCHAPPWZSKSCFDO) return("DpchAppWzskScfDo");
		if (ix == DPCHAPPWZSKSCFGEOMDO) return("DpchAppWzskScfGeomDo");
		if (ix == DPCHAPPWZSKSES1NSHOTDATA) return("DpchAppWzskSes1NShotData");
		if (ix == DPCHAPPWZSKSES1NSHOTDO) return("DpchAppWzskSes1NShotDo");
		if (ix == DPCHAPPWZSKSESDETAILDATA) return("DpchAppWzskSesDetailData");
		if (ix == DPCHAPPWZSKSESDETAILDO) return("DpchAppWzskSesDetailDo");
		if (ix == DPCHAPPWZSKSESDO) return("DpchAppWzskSesDo");
		if (ix == DPCHAPPWZSKSESLISTDATA) return("DpchAppWzskSesListData");
		if (ix == DPCHAPPWZSKSESLISTDO) return("DpchAppWzskSesListDo");
		if (ix == DPCHAPPWZSKSESRECDO) return("DpchAppWzskSesRecDo");
		if (ix == DPCHAPPWZSKSHTAPARDATA) return("DpchAppWzskShtAParData");
		if (ix == DPCHAPPWZSKSHTAPARDO) return("DpchAppWzskShtAParDo");
		if (ix == DPCHAPPWZSKSHTDETAILDATA) return("DpchAppWzskShtDetailData");
		if (ix == DPCHAPPWZSKSHTDETAILDO) return("DpchAppWzskShtDetailDo");
		if (ix == DPCHAPPWZSKSHTDO) return("DpchAppWzskShtDo");
		if (ix == DPCHAPPWZSKSHTLISTDATA) return("DpchAppWzskShtListData");
		if (ix == DPCHAPPWZSKSHTLISTDO) return("DpchAppWzskShtListDo");
		if (ix == DPCHAPPWZSKSHTRECDO) return("DpchAppWzskShtRecDo");
		if (ix == DPCHAPPWZSKSHTREF1NFILEDATA) return("DpchAppWzskShtRef1NFileData");
		if (ix == DPCHAPPWZSKSHTREF1NFILEDO) return("DpchAppWzskShtRef1NFileDo");
		if (ix == DPCHAPPWZSKUSGAACCESSDATA) return("DpchAppWzskUsgAAccessData");
		if (ix == DPCHAPPWZSKUSGAACCESSDO) return("DpchAppWzskUsgAAccessDo");
		if (ix == DPCHAPPWZSKUSGDETAILDATA) return("DpchAppWzskUsgDetailData");
		if (ix == DPCHAPPWZSKUSGDETAILDO) return("DpchAppWzskUsgDetailDo");
		if (ix == DPCHAPPWZSKUSGDO) return("DpchAppWzskUsgDo");
		if (ix == DPCHAPPWZSKUSGLISTDATA) return("DpchAppWzskUsgListData");
		if (ix == DPCHAPPWZSKUSGLISTDO) return("DpchAppWzskUsgListDo");
		if (ix == DPCHAPPWZSKUSGMNUSERDATA) return("DpchAppWzskUsgMNUserData");
		if (ix == DPCHAPPWZSKUSGMNUSERDO) return("DpchAppWzskUsgMNUserDo");
		if (ix == DPCHAPPWZSKUSGRECDO) return("DpchAppWzskUsgRecDo");
		if (ix == DPCHAPPWZSKUSR1NSESSIONDATA) return("DpchAppWzskUsr1NSessionData");
		if (ix == DPCHAPPWZSKUSR1NSESSIONDO) return("DpchAppWzskUsr1NSessionDo");
		if (ix == DPCHAPPWZSKUSRAACCESSDATA) return("DpchAppWzskUsrAAccessData");
		if (ix == DPCHAPPWZSKUSRAACCESSDO) return("DpchAppWzskUsrAAccessDo");
		if (ix == DPCHAPPWZSKUSRDETAILDATA) return("DpchAppWzskUsrDetailData");
		if (ix == DPCHAPPWZSKUSRDETAILDO) return("DpchAppWzskUsrDetailDo");
		if (ix == DPCHAPPWZSKUSRDO) return("DpchAppWzskUsrDo");
		if (ix == DPCHAPPWZSKUSRLISTDATA) return("DpchAppWzskUsrListData");
		if (ix == DPCHAPPWZSKUSRLISTDO) return("DpchAppWzskUsrListDo");
		if (ix == DPCHAPPWZSKUSRMNUSERGROUPDATA) return("DpchAppWzskUsrMNUsergroupData");
		if (ix == DPCHAPPWZSKUSRMNUSERGROUPDO) return("DpchAppWzskUsrMNUsergroupDo");
		if (ix == DPCHAPPWZSKUSRRECDO) return("DpchAppWzskUsrRecDo");

		return "";
	};
};

