/**
	* \file Wzsk.idl
	* Wzsk DDS publisher interface description for RTI Code Generator
	* \copyright (C) 2018-2020 MPSI Technologies GmbH
	* \author Alexander Wirthmueller (auto-generation)
	* \date created: 12 Oct 2025
  */
// IP header --- ABOVE

typedef char tinyint;
typedef octet utinyint;
typedef short smallint;
typedef unsigned short usmallint;
typedef long int;
typedef unsigned long uint;
typedef long long bigint;
typedef unsigned long long ubigint;

struct DdsFloatmat {
	sequence<float> vec;
	uint M;
	uint N;
};

struct DdsDoublemat {
	sequence<double> vec;
	uint M;
	uint N;
};

typedef string<65536> stringvec;
typedef string<50> vecsref;

module DdsJobWzskAcqCorner {
	struct setRoi_req {
		int roiX0;
		int roiY0;
		int roiX1;
		int roiY1;
	};

	struct setRoi_reply {
		boolean success;
	};

	struct roiX0RoiY0RoiX1RoiY1 {
		int roiX0;
		int roiY0;
		int roiX1;
		int roiY1;
	};

	struct shiftScoreMinScoreMax {
		utinyint shift;
		utinyint scoreMin;
		utinyint scoreMax;
	};
};

module DdsJobWzskAcqTrace {
	struct setRoi_req {
		int roiX0;
		int roiY0;
		int roiX1;
		int roiY1;
	};

	struct setRoi_reply {
		boolean success;
	};

	struct roiX0RoiY0RoiX1RoiY1 {
		int roiX0;
		int roiY0;
		int roiX1;
		int roiY1;
	};
};

module DdsJobWzskActLaser {
	struct setLeft_req {
		float left;
	};

	struct setLeft_reply {
		boolean success;
	};

	struct setRight_req {
		float right;
	};

	struct setRight_reply {
		boolean success;
	};

	struct leftRight {
		float left;
		float right;
	};
};

module DdsJobWzskActRotary {
	struct moveto_req {
		float target;
	};

	struct moveto_reply {
		boolean success;
	};

	struct stop_req {
		boolean dummy;
	};

	struct stop_reply {
		boolean success;
	};

	struct turn_req {
		boolean ccwNotCw;
	};

	struct turn_reply {
		boolean success;
	};

	struct zero_req {
		boolean dummy;
	};

	struct zero_reply {
		boolean success;
	};

	struct angleTarget {
		float angle;
		float target;
	};
};

module DdsJobWzskSrcFpgainfo {
	struct hdrDRdHdrDWr {
		float hdrDRd;
		float hdrDWr;
	};

	struct rndDRdRndDWr {
		float rndDRd;
		float rndDWr;
	};
};

module DdsJobWzskSrcSysinfo {
	struct loadAllLoadCore0LoadCore1LoadCore2LoadCore3 {
		sequence<float, 60> loadAll;
		sequence<float, 60> loadCore0;
		sequence<float, 60> loadCore1;
		sequence<float, 60> loadCore2;
		sequence<float, 60> loadCore3;
	};

	struct temp {
		sequence<float, 60> _temp;
	};
};
