# file Makefile.inc
# make file paths for Wzsk combined daemon, release wzskcmbd_linux
# author Catherine Johnson
# date created: 13 Oct 2020
# modified: 13 Oct 2020

SRCROOT = ${WHIZROOT}/src
LIBROOT = ${WHIZROOT}/lib
BINROOT = ${WHIZROOT}/bin
NDDSHOME = /home/mpsitech/rti_connext_dds-6.0.1
UASDKROOT = /home/mpsitech/flex_R410_1

