/**
	* \file VecWzskVDpch.h
	* vector VecWzskVDpch (implementation)
	* \copyright (C) 2016-2020 MPSI Technologies GmbH
	* \author Alexander Wirthmueller (auto-generation)
	* \date created: 1 Jul 2025
  */
// IP header --- ABOVE

#include "VecWzskVDpch.h"

using namespace std;
using namespace Sbecore;

/******************************************************************************
 namespace VecWzskVDpch
 ******************************************************************************/

uint VecWzskVDpch::getIx(
			const string& sref
		) {
	string s = StrMod::lc(sref);

	if (s == "dpchengdlgwzskfildownloaddata") return DPCHENGDLGWZSKFILDOWNLOADDATA;
	if (s == "dpchengdlgwzsknavloainidata") return DPCHENGDLGWZSKNAVLOAINIDATA;
	if (s == "dpchengm2msesswzskdata") return DPCHENGM2MSESSWZSKDATA;
	if (s == "dpchengrootwzskdata") return DPCHENGROOTWZSKDATA;
	if (s == "dpchengsesswzskdata") return DPCHENGSESSWZSKDATA;
	if (s == "dpchengwzskack") return DPCHENGWZSKACK;
	if (s == "dpchengwzskalert") return DPCHENGWZSKALERT;
	if (s == "dpchengwzskconfirm") return DPCHENGWZSKCONFIRM;
	if (s == "dpchengwzskfildata") return DPCHENGWZSKFILDATA;
	if (s == "dpchengwzskfildetaildata") return DPCHENGWZSKFILDETAILDATA;
	if (s == "dpchengwzskfilheadbardata") return DPCHENGWZSKFILHEADBARDATA;
	if (s == "dpchengwzskfillistdata") return DPCHENGWZSKFILLISTDATA;
	if (s == "dpchengwzskfilrecdata") return DPCHENGWZSKFILRECDATA;
	if (s == "dpchengwzskhwcasysdata") return DPCHENGWZSKHWCASYSDATA;
	if (s == "dpchengwzskhwcconfigalign") return DPCHENGWZSKHWCCONFIGALIGN;
	if (s == "dpchengwzskhwcconfigdata") return DPCHENGWZSKHWCCONFIGDATA;
	if (s == "dpchengwzskhwcconfiglive") return DPCHENGWZSKHWCCONFIGLIVE;
	if (s == "dpchengwzskhwcdata") return DPCHENGWZSKHWCDATA;
	if (s == "dpchengwzskhwcdebugdata") return DPCHENGWZSKHWCDEBUGDATA;
	if (s == "dpchengwzskhwcheadbardata") return DPCHENGWZSKHWCHEADBARDATA;
	if (s == "dpchengwzskllvdata") return DPCHENGWZSKLLVDATA;
	if (s == "dpchengwzskllvheadbardata") return DPCHENGWZSKLLVHEADBARDATA;
	if (s == "dpchengwzskllvidentdata") return DPCHENGWZSKLLVIDENTDATA;
	if (s == "dpchengwzskllvlaserdata") return DPCHENGWZSKLLVLASERDATA;
	if (s == "dpchengwzskllvrotarydata") return DPCHENGWZSKLLVROTARYDATA;
	if (s == "dpchengwzskllvsysmondata") return DPCHENGWZSKLLVSYSMONDATA;
	if (s == "dpchengwzskllvsysmonlive") return DPCHENGWZSKLLVSYSMONLIVE;
	if (s == "dpchengwzskllvtermdcvspdata") return DPCHENGWZSKLLVTERMDCVSPDATA;
	if (s == "dpchengwzskllvtermtivspdata") return DPCHENGWZSKLLVTERMTIVSPDATA;
	if (s == "dpchengwzskllvtermzuvspdata") return DPCHENGWZSKLLVTERMZUVSPDATA;
	if (s == "dpchengwzsknavadmindata") return DPCHENGWZSKNAVADMINDATA;
	if (s == "dpchengwzsknavdata") return DPCHENGWZSKNAVDATA;
	if (s == "dpchengwzsknavheadbardata") return DPCHENGWZSKNAVHEADBARDATA;
	if (s == "dpchengwzsknavopdata") return DPCHENGWZSKNAVOPDATA;
	if (s == "dpchengwzskprfacqcornerdata") return DPCHENGWZSKPRFACQCORNERDATA;
	if (s == "dpchengwzskprfacqpreviewdata") return DPCHENGWZSKPRFACQPREVIEWDATA;
	if (s == "dpchengwzskprfacqtracedata") return DPCHENGWZSKPRFACQTRACEDATA;
	if (s == "dpchengwzskprfactlaserdata") return DPCHENGWZSKPRFACTLASERDATA;
	if (s == "dpchengwzskprfactvistorotdata") return DPCHENGWZSKPRFACTVISTOROTDATA;
	if (s == "dpchengwzskprfdaemondata") return DPCHENGWZSKPRFDAEMONDATA;
	if (s == "dpchengwzskprfdata") return DPCHENGWZSKPRFDATA;
	if (s == "dpchengwzskprfglobaldata") return DPCHENGWZSKPRFGLOBALDATA;
	if (s == "dpchengwzskprfheadbardata") return DPCHENGWZSKPRFHEADBARDATA;
	if (s == "dpchengwzskprfsrcdcvspdata") return DPCHENGWZSKPRFSRCDCVSPDATA;
	if (s == "dpchengwzskprfsrcsysinfodata") return DPCHENGWZSKPRFSRCSYSINFODATA;
	if (s == "dpchengwzskprfsrctivspdata") return DPCHENGWZSKPRFSRCTIVSPDATA;
	if (s == "dpchengwzskprfsrczuvspdata") return DPCHENGWZSKPRFSRCZUVSPDATA;
	if (s == "dpchengwzskprsadetaildata") return DPCHENGWZSKPRSADETAILDATA;
	if (s == "dpchengwzskprsdata") return DPCHENGWZSKPRSDATA;
	if (s == "dpchengwzskprsdetaildata") return DPCHENGWZSKPRSDETAILDATA;
	if (s == "dpchengwzskprsheadbardata") return DPCHENGWZSKPRSHEADBARDATA;
	if (s == "dpchengwzskprslistdata") return DPCHENGWZSKPRSLISTDATA;
	if (s == "dpchengwzskprsrecdata") return DPCHENGWZSKPRSRECDATA;
	if (s == "dpchengwzsksuspend") return DPCHENGWZSKSUSPEND;
	if (s == "dpchengwzskusgaaccessdata") return DPCHENGWZSKUSGAACCESSDATA;
	if (s == "dpchengwzskusgdata") return DPCHENGWZSKUSGDATA;
	if (s == "dpchengwzskusgdetaildata") return DPCHENGWZSKUSGDETAILDATA;
	if (s == "dpchengwzskusgheadbardata") return DPCHENGWZSKUSGHEADBARDATA;
	if (s == "dpchengwzskusglistdata") return DPCHENGWZSKUSGLISTDATA;
	if (s == "dpchengwzskusgmnuserdata") return DPCHENGWZSKUSGMNUSERDATA;
	if (s == "dpchengwzskusgrecdata") return DPCHENGWZSKUSGRECDATA;
	if (s == "dpchengwzskusr1nsessiondata") return DPCHENGWZSKUSR1NSESSIONDATA;
	if (s == "dpchengwzskusraaccessdata") return DPCHENGWZSKUSRAACCESSDATA;
	if (s == "dpchengwzskusrdata") return DPCHENGWZSKUSRDATA;
	if (s == "dpchengwzskusrdetaildata") return DPCHENGWZSKUSRDETAILDATA;
	if (s == "dpchengwzskusrheadbardata") return DPCHENGWZSKUSRHEADBARDATA;
	if (s == "dpchengwzskusrlistdata") return DPCHENGWZSKUSRLISTDATA;
	if (s == "dpchengwzskusrmnusergroupdata") return DPCHENGWZSKUSRMNUSERGROUPDATA;
	if (s == "dpchengwzskusrrecdata") return DPCHENGWZSKUSRRECDATA;
	if (s == "dpchengwzskvtrconfigalign") return DPCHENGWZSKVTRCONFIGALIGN;
	if (s == "dpchengwzskvtrconfigdata") return DPCHENGWZSKVTRCONFIGDATA;
	if (s == "dpchengwzskvtrconfiglive") return DPCHENGWZSKVTRCONFIGLIVE;
	if (s == "dpchengwzskvtrdata") return DPCHENGWZSKVTRDATA;
	if (s == "dpchengwzskvtrdebugdata") return DPCHENGWZSKVTRDEBUGDATA;
	if (s == "dpchengwzskvtrheadbardata") return DPCHENGWZSKVTRHEADBARDATA;
	if (s == "dpchengwzskvtrmonitordata") return DPCHENGWZSKVTRMONITORDATA;
	if (s == "dpchengwzskvtrmonitorlive") return DPCHENGWZSKVTRMONITORLIVE;
	if (s == "dpchappdlgwzskfildownloaddo") return DPCHAPPDLGWZSKFILDOWNLOADDO;
	if (s == "dpchappdlgwzsknavloainidata") return DPCHAPPDLGWZSKNAVLOAINIDATA;
	if (s == "dpchappdlgwzsknavloainido") return DPCHAPPDLGWZSKNAVLOAINIDO;
	if (s == "dpchapprootwzsklogin") return DPCHAPPROOTWZSKLOGIN;
	if (s == "dpchappwzskalert") return DPCHAPPWZSKALERT;
	if (s == "dpchappwzskfildetaildata") return DPCHAPPWZSKFILDETAILDATA;
	if (s == "dpchappwzskfildetaildo") return DPCHAPPWZSKFILDETAILDO;
	if (s == "dpchappwzskfildo") return DPCHAPPWZSKFILDO;
	if (s == "dpchappwzskfillistdata") return DPCHAPPWZSKFILLISTDATA;
	if (s == "dpchappwzskfillistdo") return DPCHAPPWZSKFILLISTDO;
	if (s == "dpchappwzskfilrecdo") return DPCHAPPWZSKFILRECDO;
	if (s == "dpchappwzskhwcasysdo") return DPCHAPPWZSKHWCASYSDO;
	if (s == "dpchappwzskhwcconfigalign") return DPCHAPPWZSKHWCCONFIGALIGN;
	if (s == "dpchappwzskhwcconfigdata") return DPCHAPPWZSKHWCCONFIGDATA;
	if (s == "dpchappwzskhwcconfigdo") return DPCHAPPWZSKHWCCONFIGDO;
	if (s == "dpchappwzskhwcdebugdata") return DPCHAPPWZSKHWCDEBUGDATA;
	if (s == "dpchappwzskhwcdebugdo") return DPCHAPPWZSKHWCDEBUGDO;
	if (s == "dpchappwzskhwcdo") return DPCHAPPWZSKHWCDO;
	if (s == "dpchappwzskinit") return DPCHAPPWZSKINIT;
	if (s == "dpchappwzskllvdo") return DPCHAPPWZSKLLVDO;
	if (s == "dpchappwzskllvidentdo") return DPCHAPPWZSKLLVIDENTDO;
	if (s == "dpchappwzskllvlaserdata") return DPCHAPPWZSKLLVLASERDATA;
	if (s == "dpchappwzskllvlaserdo") return DPCHAPPWZSKLLVLASERDO;
	if (s == "dpchappwzskllvrotarydata") return DPCHAPPWZSKLLVROTARYDATA;
	if (s == "dpchappwzskllvrotarydo") return DPCHAPPWZSKLLVROTARYDO;
	if (s == "dpchappwzskllvsysmondo") return DPCHAPPWZSKLLVSYSMONDO;
	if (s == "dpchappwzskllvtermdcvspdata") return DPCHAPPWZSKLLVTERMDCVSPDATA;
	if (s == "dpchappwzskllvtermdcvspdo") return DPCHAPPWZSKLLVTERMDCVSPDO;
	if (s == "dpchappwzskllvtermtivspdata") return DPCHAPPWZSKLLVTERMTIVSPDATA;
	if (s == "dpchappwzskllvtermtivspdo") return DPCHAPPWZSKLLVTERMTIVSPDO;
	if (s == "dpchappwzskllvtermzuvspdata") return DPCHAPPWZSKLLVTERMZUVSPDATA;
	if (s == "dpchappwzskllvtermzuvspdo") return DPCHAPPWZSKLLVTERMZUVSPDO;
	if (s == "dpchappwzsknavadmindata") return DPCHAPPWZSKNAVADMINDATA;
	if (s == "dpchappwzsknavadmindo") return DPCHAPPWZSKNAVADMINDO;
	if (s == "dpchappwzsknavdo") return DPCHAPPWZSKNAVDO;
	if (s == "dpchappwzsknavopdata") return DPCHAPPWZSKNAVOPDATA;
	if (s == "dpchappwzsknavopdo") return DPCHAPPWZSKNAVOPDO;
	if (s == "dpchappwzskprfacqcornerdata") return DPCHAPPWZSKPRFACQCORNERDATA;
	if (s == "dpchappwzskprfacqcornerdo") return DPCHAPPWZSKPRFACQCORNERDO;
	if (s == "dpchappwzskprfacqpreviewdata") return DPCHAPPWZSKPRFACQPREVIEWDATA;
	if (s == "dpchappwzskprfacqpreviewdo") return DPCHAPPWZSKPRFACQPREVIEWDO;
	if (s == "dpchappwzskprfacqtracedata") return DPCHAPPWZSKPRFACQTRACEDATA;
	if (s == "dpchappwzskprfacqtracedo") return DPCHAPPWZSKPRFACQTRACEDO;
	if (s == "dpchappwzskprfactlaserdata") return DPCHAPPWZSKPRFACTLASERDATA;
	if (s == "dpchappwzskprfactlaserdo") return DPCHAPPWZSKPRFACTLASERDO;
	if (s == "dpchappwzskprfactvistorotdata") return DPCHAPPWZSKPRFACTVISTOROTDATA;
	if (s == "dpchappwzskprfactvistorotdo") return DPCHAPPWZSKPRFACTVISTOROTDO;
	if (s == "dpchappwzskprfdaemondata") return DPCHAPPWZSKPRFDAEMONDATA;
	if (s == "dpchappwzskprfdaemondo") return DPCHAPPWZSKPRFDAEMONDO;
	if (s == "dpchappwzskprfdo") return DPCHAPPWZSKPRFDO;
	if (s == "dpchappwzskprfglobaldata") return DPCHAPPWZSKPRFGLOBALDATA;
	if (s == "dpchappwzskprfglobaldo") return DPCHAPPWZSKPRFGLOBALDO;
	if (s == "dpchappwzskprfsrcdcvspdata") return DPCHAPPWZSKPRFSRCDCVSPDATA;
	if (s == "dpchappwzskprfsrcdcvspdo") return DPCHAPPWZSKPRFSRCDCVSPDO;
	if (s == "dpchappwzskprfsrcsysinfodata") return DPCHAPPWZSKPRFSRCSYSINFODATA;
	if (s == "dpchappwzskprfsrcsysinfodo") return DPCHAPPWZSKPRFSRCSYSINFODO;
	if (s == "dpchappwzskprfsrctivspdata") return DPCHAPPWZSKPRFSRCTIVSPDATA;
	if (s == "dpchappwzskprfsrctivspdo") return DPCHAPPWZSKPRFSRCTIVSPDO;
	if (s == "dpchappwzskprfsrczuvspdata") return DPCHAPPWZSKPRFSRCZUVSPDATA;
	if (s == "dpchappwzskprfsrczuvspdo") return DPCHAPPWZSKPRFSRCZUVSPDO;
	if (s == "dpchappwzskprsadetaildata") return DPCHAPPWZSKPRSADETAILDATA;
	if (s == "dpchappwzskprsadetaildo") return DPCHAPPWZSKPRSADETAILDO;
	if (s == "dpchappwzskprsdetaildata") return DPCHAPPWZSKPRSDETAILDATA;
	if (s == "dpchappwzskprsdetaildo") return DPCHAPPWZSKPRSDETAILDO;
	if (s == "dpchappwzskprsdo") return DPCHAPPWZSKPRSDO;
	if (s == "dpchappwzskprslistdata") return DPCHAPPWZSKPRSLISTDATA;
	if (s == "dpchappwzskprslistdo") return DPCHAPPWZSKPRSLISTDO;
	if (s == "dpchappwzskprsrecdo") return DPCHAPPWZSKPRSRECDO;
	if (s == "dpchappwzskresume") return DPCHAPPWZSKRESUME;
	if (s == "dpchappwzskusgaaccessdata") return DPCHAPPWZSKUSGAACCESSDATA;
	if (s == "dpchappwzskusgaaccessdo") return DPCHAPPWZSKUSGAACCESSDO;
	if (s == "dpchappwzskusgdetaildata") return DPCHAPPWZSKUSGDETAILDATA;
	if (s == "dpchappwzskusgdetaildo") return DPCHAPPWZSKUSGDETAILDO;
	if (s == "dpchappwzskusgdo") return DPCHAPPWZSKUSGDO;
	if (s == "dpchappwzskusglistdata") return DPCHAPPWZSKUSGLISTDATA;
	if (s == "dpchappwzskusglistdo") return DPCHAPPWZSKUSGLISTDO;
	if (s == "dpchappwzskusgmnuserdata") return DPCHAPPWZSKUSGMNUSERDATA;
	if (s == "dpchappwzskusgmnuserdo") return DPCHAPPWZSKUSGMNUSERDO;
	if (s == "dpchappwzskusgrecdo") return DPCHAPPWZSKUSGRECDO;
	if (s == "dpchappwzskusr1nsessiondata") return DPCHAPPWZSKUSR1NSESSIONDATA;
	if (s == "dpchappwzskusr1nsessiondo") return DPCHAPPWZSKUSR1NSESSIONDO;
	if (s == "dpchappwzskusraaccessdata") return DPCHAPPWZSKUSRAACCESSDATA;
	if (s == "dpchappwzskusraaccessdo") return DPCHAPPWZSKUSRAACCESSDO;
	if (s == "dpchappwzskusrdetaildata") return DPCHAPPWZSKUSRDETAILDATA;
	if (s == "dpchappwzskusrdetaildo") return DPCHAPPWZSKUSRDETAILDO;
	if (s == "dpchappwzskusrdo") return DPCHAPPWZSKUSRDO;
	if (s == "dpchappwzskusrlistdata") return DPCHAPPWZSKUSRLISTDATA;
	if (s == "dpchappwzskusrlistdo") return DPCHAPPWZSKUSRLISTDO;
	if (s == "dpchappwzskusrmnusergroupdata") return DPCHAPPWZSKUSRMNUSERGROUPDATA;
	if (s == "dpchappwzskusrmnusergroupdo") return DPCHAPPWZSKUSRMNUSERGROUPDO;
	if (s == "dpchappwzskusrrecdo") return DPCHAPPWZSKUSRRECDO;
	if (s == "dpchappwzskvtrconfigalign") return DPCHAPPWZSKVTRCONFIGALIGN;
	if (s == "dpchappwzskvtrconfigdata") return DPCHAPPWZSKVTRCONFIGDATA;
	if (s == "dpchappwzskvtrconfigdo") return DPCHAPPWZSKVTRCONFIGDO;
	if (s == "dpchappwzskvtrdebugdata") return DPCHAPPWZSKVTRDEBUGDATA;
	if (s == "dpchappwzskvtrdebugdo") return DPCHAPPWZSKVTRDEBUGDO;
	if (s == "dpchappwzskvtrdo") return DPCHAPPWZSKVTRDO;
	if (s == "dpchappwzskvtrmonitordo") return DPCHAPPWZSKVTRMONITORDO;

	return(0);
};

string VecWzskVDpch::getSref(
			const uint ix
		) {
	if (ix == DPCHENGDLGWZSKFILDOWNLOADDATA) return("DpchEngDlgWzskFilDownloadData");
	if (ix == DPCHENGDLGWZSKNAVLOAINIDATA) return("DpchEngDlgWzskNavLoainiData");
	if (ix == DPCHENGM2MSESSWZSKDATA) return("DpchEngM2msessWzskData");
	if (ix == DPCHENGROOTWZSKDATA) return("DpchEngRootWzskData");
	if (ix == DPCHENGSESSWZSKDATA) return("DpchEngSessWzskData");
	if (ix == DPCHENGWZSKACK) return("DpchEngWzskAck");
	if (ix == DPCHENGWZSKALERT) return("DpchEngWzskAlert");
	if (ix == DPCHENGWZSKCONFIRM) return("DpchEngWzskConfirm");
	if (ix == DPCHENGWZSKFILDATA) return("DpchEngWzskFilData");
	if (ix == DPCHENGWZSKFILDETAILDATA) return("DpchEngWzskFilDetailData");
	if (ix == DPCHENGWZSKFILHEADBARDATA) return("DpchEngWzskFilHeadbarData");
	if (ix == DPCHENGWZSKFILLISTDATA) return("DpchEngWzskFilListData");
	if (ix == DPCHENGWZSKFILRECDATA) return("DpchEngWzskFilRecData");
	if (ix == DPCHENGWZSKHWCASYSDATA) return("DpchEngWzskHwcAsysData");
	if (ix == DPCHENGWZSKHWCCONFIGALIGN) return("DpchEngWzskHwcConfigAlign");
	if (ix == DPCHENGWZSKHWCCONFIGDATA) return("DpchEngWzskHwcConfigData");
	if (ix == DPCHENGWZSKHWCCONFIGLIVE) return("DpchEngWzskHwcConfigLive");
	if (ix == DPCHENGWZSKHWCDATA) return("DpchEngWzskHwcData");
	if (ix == DPCHENGWZSKHWCDEBUGDATA) return("DpchEngWzskHwcDebugData");
	if (ix == DPCHENGWZSKHWCHEADBARDATA) return("DpchEngWzskHwcHeadbarData");
	if (ix == DPCHENGWZSKLLVDATA) return("DpchEngWzskLlvData");
	if (ix == DPCHENGWZSKLLVHEADBARDATA) return("DpchEngWzskLlvHeadbarData");
	if (ix == DPCHENGWZSKLLVIDENTDATA) return("DpchEngWzskLlvIdentData");
	if (ix == DPCHENGWZSKLLVLASERDATA) return("DpchEngWzskLlvLaserData");
	if (ix == DPCHENGWZSKLLVROTARYDATA) return("DpchEngWzskLlvRotaryData");
	if (ix == DPCHENGWZSKLLVSYSMONDATA) return("DpchEngWzskLlvSysmonData");
	if (ix == DPCHENGWZSKLLVSYSMONLIVE) return("DpchEngWzskLlvSysmonLive");
	if (ix == DPCHENGWZSKLLVTERMDCVSPDATA) return("DpchEngWzskLlvTermDcvspData");
	if (ix == DPCHENGWZSKLLVTERMTIVSPDATA) return("DpchEngWzskLlvTermTivspData");
	if (ix == DPCHENGWZSKLLVTERMZUVSPDATA) return("DpchEngWzskLlvTermZuvspData");
	if (ix == DPCHENGWZSKNAVADMINDATA) return("DpchEngWzskNavAdminData");
	if (ix == DPCHENGWZSKNAVDATA) return("DpchEngWzskNavData");
	if (ix == DPCHENGWZSKNAVHEADBARDATA) return("DpchEngWzskNavHeadbarData");
	if (ix == DPCHENGWZSKNAVOPDATA) return("DpchEngWzskNavOpData");
	if (ix == DPCHENGWZSKPRFACQCORNERDATA) return("DpchEngWzskPrfAcqCornerData");
	if (ix == DPCHENGWZSKPRFACQPREVIEWDATA) return("DpchEngWzskPrfAcqPreviewData");
	if (ix == DPCHENGWZSKPRFACQTRACEDATA) return("DpchEngWzskPrfAcqTraceData");
	if (ix == DPCHENGWZSKPRFACTLASERDATA) return("DpchEngWzskPrfActLaserData");
	if (ix == DPCHENGWZSKPRFACTVISTOROTDATA) return("DpchEngWzskPrfActVistorotData");
	if (ix == DPCHENGWZSKPRFDAEMONDATA) return("DpchEngWzskPrfDaemonData");
	if (ix == DPCHENGWZSKPRFDATA) return("DpchEngWzskPrfData");
	if (ix == DPCHENGWZSKPRFGLOBALDATA) return("DpchEngWzskPrfGlobalData");
	if (ix == DPCHENGWZSKPRFHEADBARDATA) return("DpchEngWzskPrfHeadbarData");
	if (ix == DPCHENGWZSKPRFSRCDCVSPDATA) return("DpchEngWzskPrfSrcDcvspData");
	if (ix == DPCHENGWZSKPRFSRCSYSINFODATA) return("DpchEngWzskPrfSrcSysinfoData");
	if (ix == DPCHENGWZSKPRFSRCTIVSPDATA) return("DpchEngWzskPrfSrcTivspData");
	if (ix == DPCHENGWZSKPRFSRCZUVSPDATA) return("DpchEngWzskPrfSrcZuvspData");
	if (ix == DPCHENGWZSKPRSADETAILDATA) return("DpchEngWzskPrsADetailData");
	if (ix == DPCHENGWZSKPRSDATA) return("DpchEngWzskPrsData");
	if (ix == DPCHENGWZSKPRSDETAILDATA) return("DpchEngWzskPrsDetailData");
	if (ix == DPCHENGWZSKPRSHEADBARDATA) return("DpchEngWzskPrsHeadbarData");
	if (ix == DPCHENGWZSKPRSLISTDATA) return("DpchEngWzskPrsListData");
	if (ix == DPCHENGWZSKPRSRECDATA) return("DpchEngWzskPrsRecData");
	if (ix == DPCHENGWZSKSUSPEND) return("DpchEngWzskSuspend");
	if (ix == DPCHENGWZSKUSGAACCESSDATA) return("DpchEngWzskUsgAAccessData");
	if (ix == DPCHENGWZSKUSGDATA) return("DpchEngWzskUsgData");
	if (ix == DPCHENGWZSKUSGDETAILDATA) return("DpchEngWzskUsgDetailData");
	if (ix == DPCHENGWZSKUSGHEADBARDATA) return("DpchEngWzskUsgHeadbarData");
	if (ix == DPCHENGWZSKUSGLISTDATA) return("DpchEngWzskUsgListData");
	if (ix == DPCHENGWZSKUSGMNUSERDATA) return("DpchEngWzskUsgMNUserData");
	if (ix == DPCHENGWZSKUSGRECDATA) return("DpchEngWzskUsgRecData");
	if (ix == DPCHENGWZSKUSR1NSESSIONDATA) return("DpchEngWzskUsr1NSessionData");
	if (ix == DPCHENGWZSKUSRAACCESSDATA) return("DpchEngWzskUsrAAccessData");
	if (ix == DPCHENGWZSKUSRDATA) return("DpchEngWzskUsrData");
	if (ix == DPCHENGWZSKUSRDETAILDATA) return("DpchEngWzskUsrDetailData");
	if (ix == DPCHENGWZSKUSRHEADBARDATA) return("DpchEngWzskUsrHeadbarData");
	if (ix == DPCHENGWZSKUSRLISTDATA) return("DpchEngWzskUsrListData");
	if (ix == DPCHENGWZSKUSRMNUSERGROUPDATA) return("DpchEngWzskUsrMNUsergroupData");
	if (ix == DPCHENGWZSKUSRRECDATA) return("DpchEngWzskUsrRecData");
	if (ix == DPCHENGWZSKVTRCONFIGALIGN) return("DpchEngWzskVtrConfigAlign");
	if (ix == DPCHENGWZSKVTRCONFIGDATA) return("DpchEngWzskVtrConfigData");
	if (ix == DPCHENGWZSKVTRCONFIGLIVE) return("DpchEngWzskVtrConfigLive");
	if (ix == DPCHENGWZSKVTRDATA) return("DpchEngWzskVtrData");
	if (ix == DPCHENGWZSKVTRDEBUGDATA) return("DpchEngWzskVtrDebugData");
	if (ix == DPCHENGWZSKVTRHEADBARDATA) return("DpchEngWzskVtrHeadbarData");
	if (ix == DPCHENGWZSKVTRMONITORDATA) return("DpchEngWzskVtrMonitorData");
	if (ix == DPCHENGWZSKVTRMONITORLIVE) return("DpchEngWzskVtrMonitorLive");
	if (ix == DPCHAPPDLGWZSKFILDOWNLOADDO) return("DpchAppDlgWzskFilDownloadDo");
	if (ix == DPCHAPPDLGWZSKNAVLOAINIDATA) return("DpchAppDlgWzskNavLoainiData");
	if (ix == DPCHAPPDLGWZSKNAVLOAINIDO) return("DpchAppDlgWzskNavLoainiDo");
	if (ix == DPCHAPPROOTWZSKLOGIN) return("DpchAppRootWzskLogin");
	if (ix == DPCHAPPWZSKALERT) return("DpchAppWzskAlert");
	if (ix == DPCHAPPWZSKFILDETAILDATA) return("DpchAppWzskFilDetailData");
	if (ix == DPCHAPPWZSKFILDETAILDO) return("DpchAppWzskFilDetailDo");
	if (ix == DPCHAPPWZSKFILDO) return("DpchAppWzskFilDo");
	if (ix == DPCHAPPWZSKFILLISTDATA) return("DpchAppWzskFilListData");
	if (ix == DPCHAPPWZSKFILLISTDO) return("DpchAppWzskFilListDo");
	if (ix == DPCHAPPWZSKFILRECDO) return("DpchAppWzskFilRecDo");
	if (ix == DPCHAPPWZSKHWCASYSDO) return("DpchAppWzskHwcAsysDo");
	if (ix == DPCHAPPWZSKHWCCONFIGALIGN) return("DpchAppWzskHwcConfigAlign");
	if (ix == DPCHAPPWZSKHWCCONFIGDATA) return("DpchAppWzskHwcConfigData");
	if (ix == DPCHAPPWZSKHWCCONFIGDO) return("DpchAppWzskHwcConfigDo");
	if (ix == DPCHAPPWZSKHWCDEBUGDATA) return("DpchAppWzskHwcDebugData");
	if (ix == DPCHAPPWZSKHWCDEBUGDO) return("DpchAppWzskHwcDebugDo");
	if (ix == DPCHAPPWZSKHWCDO) return("DpchAppWzskHwcDo");
	if (ix == DPCHAPPWZSKINIT) return("DpchAppWzskInit");
	if (ix == DPCHAPPWZSKLLVDO) return("DpchAppWzskLlvDo");
	if (ix == DPCHAPPWZSKLLVIDENTDO) return("DpchAppWzskLlvIdentDo");
	if (ix == DPCHAPPWZSKLLVLASERDATA) return("DpchAppWzskLlvLaserData");
	if (ix == DPCHAPPWZSKLLVLASERDO) return("DpchAppWzskLlvLaserDo");
	if (ix == DPCHAPPWZSKLLVROTARYDATA) return("DpchAppWzskLlvRotaryData");
	if (ix == DPCHAPPWZSKLLVROTARYDO) return("DpchAppWzskLlvRotaryDo");
	if (ix == DPCHAPPWZSKLLVSYSMONDO) return("DpchAppWzskLlvSysmonDo");
	if (ix == DPCHAPPWZSKLLVTERMDCVSPDATA) return("DpchAppWzskLlvTermDcvspData");
	if (ix == DPCHAPPWZSKLLVTERMDCVSPDO) return("DpchAppWzskLlvTermDcvspDo");
	if (ix == DPCHAPPWZSKLLVTERMTIVSPDATA) return("DpchAppWzskLlvTermTivspData");
	if (ix == DPCHAPPWZSKLLVTERMTIVSPDO) return("DpchAppWzskLlvTermTivspDo");
	if (ix == DPCHAPPWZSKLLVTERMZUVSPDATA) return("DpchAppWzskLlvTermZuvspData");
	if (ix == DPCHAPPWZSKLLVTERMZUVSPDO) return("DpchAppWzskLlvTermZuvspDo");
	if (ix == DPCHAPPWZSKNAVADMINDATA) return("DpchAppWzskNavAdminData");
	if (ix == DPCHAPPWZSKNAVADMINDO) return("DpchAppWzskNavAdminDo");
	if (ix == DPCHAPPWZSKNAVDO) return("DpchAppWzskNavDo");
	if (ix == DPCHAPPWZSKNAVOPDATA) return("DpchAppWzskNavOpData");
	if (ix == DPCHAPPWZSKNAVOPDO) return("DpchAppWzskNavOpDo");
	if (ix == DPCHAPPWZSKPRFACQCORNERDATA) return("DpchAppWzskPrfAcqCornerData");
	if (ix == DPCHAPPWZSKPRFACQCORNERDO) return("DpchAppWzskPrfAcqCornerDo");
	if (ix == DPCHAPPWZSKPRFACQPREVIEWDATA) return("DpchAppWzskPrfAcqPreviewData");
	if (ix == DPCHAPPWZSKPRFACQPREVIEWDO) return("DpchAppWzskPrfAcqPreviewDo");
	if (ix == DPCHAPPWZSKPRFACQTRACEDATA) return("DpchAppWzskPrfAcqTraceData");
	if (ix == DPCHAPPWZSKPRFACQTRACEDO) return("DpchAppWzskPrfAcqTraceDo");
	if (ix == DPCHAPPWZSKPRFACTLASERDATA) return("DpchAppWzskPrfActLaserData");
	if (ix == DPCHAPPWZSKPRFACTLASERDO) return("DpchAppWzskPrfActLaserDo");
	if (ix == DPCHAPPWZSKPRFACTVISTOROTDATA) return("DpchAppWzskPrfActVistorotData");
	if (ix == DPCHAPPWZSKPRFACTVISTOROTDO) return("DpchAppWzskPrfActVistorotDo");
	if (ix == DPCHAPPWZSKPRFDAEMONDATA) return("DpchAppWzskPrfDaemonData");
	if (ix == DPCHAPPWZSKPRFDAEMONDO) return("DpchAppWzskPrfDaemonDo");
	if (ix == DPCHAPPWZSKPRFDO) return("DpchAppWzskPrfDo");
	if (ix == DPCHAPPWZSKPRFGLOBALDATA) return("DpchAppWzskPrfGlobalData");
	if (ix == DPCHAPPWZSKPRFGLOBALDO) return("DpchAppWzskPrfGlobalDo");
	if (ix == DPCHAPPWZSKPRFSRCDCVSPDATA) return("DpchAppWzskPrfSrcDcvspData");
	if (ix == DPCHAPPWZSKPRFSRCDCVSPDO) return("DpchAppWzskPrfSrcDcvspDo");
	if (ix == DPCHAPPWZSKPRFSRCSYSINFODATA) return("DpchAppWzskPrfSrcSysinfoData");
	if (ix == DPCHAPPWZSKPRFSRCSYSINFODO) return("DpchAppWzskPrfSrcSysinfoDo");
	if (ix == DPCHAPPWZSKPRFSRCTIVSPDATA) return("DpchAppWzskPrfSrcTivspData");
	if (ix == DPCHAPPWZSKPRFSRCTIVSPDO) return("DpchAppWzskPrfSrcTivspDo");
	if (ix == DPCHAPPWZSKPRFSRCZUVSPDATA) return("DpchAppWzskPrfSrcZuvspData");
	if (ix == DPCHAPPWZSKPRFSRCZUVSPDO) return("DpchAppWzskPrfSrcZuvspDo");
	if (ix == DPCHAPPWZSKPRSADETAILDATA) return("DpchAppWzskPrsADetailData");
	if (ix == DPCHAPPWZSKPRSADETAILDO) return("DpchAppWzskPrsADetailDo");
	if (ix == DPCHAPPWZSKPRSDETAILDATA) return("DpchAppWzskPrsDetailData");
	if (ix == DPCHAPPWZSKPRSDETAILDO) return("DpchAppWzskPrsDetailDo");
	if (ix == DPCHAPPWZSKPRSDO) return("DpchAppWzskPrsDo");
	if (ix == DPCHAPPWZSKPRSLISTDATA) return("DpchAppWzskPrsListData");
	if (ix == DPCHAPPWZSKPRSLISTDO) return("DpchAppWzskPrsListDo");
	if (ix == DPCHAPPWZSKPRSRECDO) return("DpchAppWzskPrsRecDo");
	if (ix == DPCHAPPWZSKRESUME) return("DpchAppWzskResume");
	if (ix == DPCHAPPWZSKUSGAACCESSDATA) return("DpchAppWzskUsgAAccessData");
	if (ix == DPCHAPPWZSKUSGAACCESSDO) return("DpchAppWzskUsgAAccessDo");
	if (ix == DPCHAPPWZSKUSGDETAILDATA) return("DpchAppWzskUsgDetailData");
	if (ix == DPCHAPPWZSKUSGDETAILDO) return("DpchAppWzskUsgDetailDo");
	if (ix == DPCHAPPWZSKUSGDO) return("DpchAppWzskUsgDo");
	if (ix == DPCHAPPWZSKUSGLISTDATA) return("DpchAppWzskUsgListData");
	if (ix == DPCHAPPWZSKUSGLISTDO) return("DpchAppWzskUsgListDo");
	if (ix == DPCHAPPWZSKUSGMNUSERDATA) return("DpchAppWzskUsgMNUserData");
	if (ix == DPCHAPPWZSKUSGMNUSERDO) return("DpchAppWzskUsgMNUserDo");
	if (ix == DPCHAPPWZSKUSGRECDO) return("DpchAppWzskUsgRecDo");
	if (ix == DPCHAPPWZSKUSR1NSESSIONDATA) return("DpchAppWzskUsr1NSessionData");
	if (ix == DPCHAPPWZSKUSR1NSESSIONDO) return("DpchAppWzskUsr1NSessionDo");
	if (ix == DPCHAPPWZSKUSRAACCESSDATA) return("DpchAppWzskUsrAAccessData");
	if (ix == DPCHAPPWZSKUSRAACCESSDO) return("DpchAppWzskUsrAAccessDo");
	if (ix == DPCHAPPWZSKUSRDETAILDATA) return("DpchAppWzskUsrDetailData");
	if (ix == DPCHAPPWZSKUSRDETAILDO) return("DpchAppWzskUsrDetailDo");
	if (ix == DPCHAPPWZSKUSRDO) return("DpchAppWzskUsrDo");
	if (ix == DPCHAPPWZSKUSRLISTDATA) return("DpchAppWzskUsrListData");
	if (ix == DPCHAPPWZSKUSRLISTDO) return("DpchAppWzskUsrListDo");
	if (ix == DPCHAPPWZSKUSRMNUSERGROUPDATA) return("DpchAppWzskUsrMNUsergroupData");
	if (ix == DPCHAPPWZSKUSRMNUSERGROUPDO) return("DpchAppWzskUsrMNUsergroupDo");
	if (ix == DPCHAPPWZSKUSRRECDO) return("DpchAppWzskUsrRecDo");
	if (ix == DPCHAPPWZSKVTRCONFIGALIGN) return("DpchAppWzskVtrConfigAlign");
	if (ix == DPCHAPPWZSKVTRCONFIGDATA) return("DpchAppWzskVtrConfigData");
	if (ix == DPCHAPPWZSKVTRCONFIGDO) return("DpchAppWzskVtrConfigDo");
	if (ix == DPCHAPPWZSKVTRDEBUGDATA) return("DpchAppWzskVtrDebugData");
	if (ix == DPCHAPPWZSKVTRDEBUGDO) return("DpchAppWzskVtrDebugDo");
	if (ix == DPCHAPPWZSKVTRDO) return("DpchAppWzskVtrDo");
	if (ix == DPCHAPPWZSKVTRMONITORDO) return("DpchAppWzskVtrMonitorDo");

	return("");
};
