/**
	* \file VecWzskVDpch.h
	* vector VecWzskVDpch (declarations)
	* \author Catherine Johnson
	* \date created: 23 Jul 2020
	* \date modified: 23 Jul 2020
	*/

#ifndef VECWZSKVDPCH_H
#define VECWZSKVDPCH_H

#include <sbecore/Xmlio.h>

/**
	* VecWzskVDpch
	*/
namespace VecWzskVDpch {
	const Sbecore::uint DPCHENGDLGWZSKFILDOWNLOADDATA = 1;
	const Sbecore::uint DPCHENGDLGWZSKNAVLOAINIDATA = 2;
	const Sbecore::uint DPCHENGDLGWZSKOBJNEWDATA = 3;
	const Sbecore::uint DPCHENGDLGWZSKOGRNEWDATA = 4;
	const Sbecore::uint DPCHENGDLGWZSKSCFCAMERAMATDATA = 5;
	const Sbecore::uint DPCHENGDLGWZSKSCFLASERPOSDATA = 6;
	const Sbecore::uint DPCHENGDLGWZSKSCFTTABLECOORDDATA = 7;
	const Sbecore::uint DPCHENGM2MSESSWZSKDATA = 8;
	const Sbecore::uint DPCHENGROOTWZSKDATA = 9;
	const Sbecore::uint DPCHENGSESSWZSKDATA = 10;
	const Sbecore::uint DPCHENGWZSKACK = 11;
	const Sbecore::uint DPCHENGWZSKALERT = 12;
	const Sbecore::uint DPCHENGWZSKCONFIRM = 13;
	const Sbecore::uint DPCHENGWZSKFILDATA = 14;
	const Sbecore::uint DPCHENGWZSKFILDETAILDATA = 15;
	const Sbecore::uint DPCHENGWZSKFILHEADBARDATA = 16;
	const Sbecore::uint DPCHENGWZSKFILLISTDATA = 17;
	const Sbecore::uint DPCHENGWZSKFILRECDATA = 18;
	const Sbecore::uint DPCHENGWZSKLIV2DVIEWALIGN = 19;
	const Sbecore::uint DPCHENGWZSKLIV2DVIEWDATA = 20;
	const Sbecore::uint DPCHENGWZSKLIV2DVIEWLIVE = 21;
	const Sbecore::uint DPCHENGWZSKLIV3DVIEWDATA = 22;
	const Sbecore::uint DPCHENGWZSKLIV3DVIEWLIVE = 23;
	const Sbecore::uint DPCHENGWZSKLIVDATA = 24;
	const Sbecore::uint DPCHENGWZSKLIVHEADBARDATA = 25;
	const Sbecore::uint DPCHENGWZSKLLVCAMERADATA = 26;
	const Sbecore::uint DPCHENGWZSKLLVCAMERALIVE = 27;
	const Sbecore::uint DPCHENGWZSKLLVDATA = 28;
	const Sbecore::uint DPCHENGWZSKLLVHEADBARDATA = 29;
	const Sbecore::uint DPCHENGWZSKLLVLASERDATA = 30;
	const Sbecore::uint DPCHENGWZSKLLVTERMDATA = 31;
	const Sbecore::uint DPCHENGWZSKLLVTTABLEDATA = 32;
	const Sbecore::uint DPCHENGWZSKNAVADMINDATA = 33;
	const Sbecore::uint DPCHENGWZSKNAVDATA = 34;
	const Sbecore::uint DPCHENGWZSKNAVGALERYDATA = 35;
	const Sbecore::uint DPCHENGWZSKNAVHEADBARDATA = 36;
	const Sbecore::uint DPCHENGWZSKNAVOPDATA = 37;
	const Sbecore::uint DPCHENGWZSKNAVPREDATA = 38;
	const Sbecore::uint DPCHENGWZSKOBJDATA = 39;
	const Sbecore::uint DPCHENGWZSKOBJDETAILDATA = 40;
	const Sbecore::uint DPCHENGWZSKOBJHEADBARDATA = 41;
	const Sbecore::uint DPCHENGWZSKOBJLISTDATA = 42;
	const Sbecore::uint DPCHENGWZSKOBJRECDATA = 43;
	const Sbecore::uint DPCHENGWZSKOBJREF1NFILEDATA = 44;
	const Sbecore::uint DPCHENGWZSKOGR1NOBJECTDATA = 45;
	const Sbecore::uint DPCHENGWZSKOGR1NSHOTDATA = 46;
	const Sbecore::uint DPCHENGWZSKOGRDATA = 47;
	const Sbecore::uint DPCHENGWZSKOGRDETAILDATA = 48;
	const Sbecore::uint DPCHENGWZSKOGRHEADBARDATA = 49;
	const Sbecore::uint DPCHENGWZSKOGRLISTDATA = 50;
	const Sbecore::uint DPCHENGWZSKOGRRECDATA = 51;
	const Sbecore::uint DPCHENGWZSKOGRSUP1NOBJGROUPDATA = 52;
	const Sbecore::uint DPCHENGWZSKPRSADETAILDATA = 53;
	const Sbecore::uint DPCHENGWZSKPRSDATA = 54;
	const Sbecore::uint DPCHENGWZSKPRSDETAILDATA = 55;
	const Sbecore::uint DPCHENGWZSKPRSHEADBARDATA = 56;
	const Sbecore::uint DPCHENGWZSKPRSLISTDATA = 57;
	const Sbecore::uint DPCHENGWZSKPRSRECDATA = 58;
	const Sbecore::uint DPCHENGWZSKSCFCONNDATA = 59;
	const Sbecore::uint DPCHENGWZSKSCFDATA = 60;
	const Sbecore::uint DPCHENGWZSKSCFGEOMDATA = 61;
	const Sbecore::uint DPCHENGWZSKSCFHEADBARDATA = 62;
	const Sbecore::uint DPCHENGWZSKSES1NSHOTDATA = 63;
	const Sbecore::uint DPCHENGWZSKSESDATA = 64;
	const Sbecore::uint DPCHENGWZSKSESDETAILDATA = 65;
	const Sbecore::uint DPCHENGWZSKSESHEADBARDATA = 66;
	const Sbecore::uint DPCHENGWZSKSESLISTDATA = 67;
	const Sbecore::uint DPCHENGWZSKSESRECDATA = 68;
	const Sbecore::uint DPCHENGWZSKSHTAPARDATA = 69;
	const Sbecore::uint DPCHENGWZSKSHTDATA = 70;
	const Sbecore::uint DPCHENGWZSKSHTDETAILDATA = 71;
	const Sbecore::uint DPCHENGWZSKSHTHEADBARDATA = 72;
	const Sbecore::uint DPCHENGWZSKSHTLISTDATA = 73;
	const Sbecore::uint DPCHENGWZSKSHTRECDATA = 74;
	const Sbecore::uint DPCHENGWZSKSHTREF1NFILEDATA = 75;
	const Sbecore::uint DPCHENGWZSKSUSPEND = 76;
	const Sbecore::uint DPCHENGWZSKUSGAACCESSDATA = 77;
	const Sbecore::uint DPCHENGWZSKUSGDATA = 78;
	const Sbecore::uint DPCHENGWZSKUSGDETAILDATA = 79;
	const Sbecore::uint DPCHENGWZSKUSGHEADBARDATA = 80;
	const Sbecore::uint DPCHENGWZSKUSGLISTDATA = 81;
	const Sbecore::uint DPCHENGWZSKUSGMNUSERDATA = 82;
	const Sbecore::uint DPCHENGWZSKUSGRECDATA = 83;
	const Sbecore::uint DPCHENGWZSKUSR1NSESSIONDATA = 84;
	const Sbecore::uint DPCHENGWZSKUSRAACCESSDATA = 85;
	const Sbecore::uint DPCHENGWZSKUSRDATA = 86;
	const Sbecore::uint DPCHENGWZSKUSRDETAILDATA = 87;
	const Sbecore::uint DPCHENGWZSKUSRHEADBARDATA = 88;
	const Sbecore::uint DPCHENGWZSKUSRLISTDATA = 89;
	const Sbecore::uint DPCHENGWZSKUSRMNUSERGROUPDATA = 90;
	const Sbecore::uint DPCHENGWZSKUSRRECDATA = 91;
	const Sbecore::uint DPCHAPPDLGWZSKFILDOWNLOADDO = 92;
	const Sbecore::uint DPCHAPPDLGWZSKNAVLOAINIDATA = 93;
	const Sbecore::uint DPCHAPPDLGWZSKNAVLOAINIDO = 94;
	const Sbecore::uint DPCHAPPDLGWZSKOBJNEWDATA = 95;
	const Sbecore::uint DPCHAPPDLGWZSKOBJNEWDO = 96;
	const Sbecore::uint DPCHAPPDLGWZSKOGRNEWDATA = 97;
	const Sbecore::uint DPCHAPPDLGWZSKOGRNEWDO = 98;
	const Sbecore::uint DPCHAPPDLGWZSKSCFCAMERAMATDATA = 99;
	const Sbecore::uint DPCHAPPDLGWZSKSCFCAMERAMATDO = 100;
	const Sbecore::uint DPCHAPPDLGWZSKSCFLASERPOSDATA = 101;
	const Sbecore::uint DPCHAPPDLGWZSKSCFLASERPOSDO = 102;
	const Sbecore::uint DPCHAPPDLGWZSKSCFTTABLECOORDDATA = 103;
	const Sbecore::uint DPCHAPPDLGWZSKSCFTTABLECOORDDO = 104;
	const Sbecore::uint DPCHAPPROOTWZSKLOGIN = 105;
	const Sbecore::uint DPCHAPPWZSKALERT = 106;
	const Sbecore::uint DPCHAPPWZSKFILDETAILDATA = 107;
	const Sbecore::uint DPCHAPPWZSKFILDETAILDO = 108;
	const Sbecore::uint DPCHAPPWZSKFILDO = 109;
	const Sbecore::uint DPCHAPPWZSKFILLISTDATA = 110;
	const Sbecore::uint DPCHAPPWZSKFILLISTDO = 111;
	const Sbecore::uint DPCHAPPWZSKFILRECDO = 112;
	const Sbecore::uint DPCHAPPWZSKINIT = 113;
	const Sbecore::uint DPCHAPPWZSKLIV2DVIEWALIGN = 114;
	const Sbecore::uint DPCHAPPWZSKLIV2DVIEWDATA = 115;
	const Sbecore::uint DPCHAPPWZSKLIV2DVIEWDO = 116;
	const Sbecore::uint DPCHAPPWZSKLIV3DVIEWDO = 117;
	const Sbecore::uint DPCHAPPWZSKLIVDO = 118;
	const Sbecore::uint DPCHAPPWZSKLLVCAMERADATA = 119;
	const Sbecore::uint DPCHAPPWZSKLLVCAMERADO = 120;
	const Sbecore::uint DPCHAPPWZSKLLVDO = 121;
	const Sbecore::uint DPCHAPPWZSKLLVLASERDATA = 122;
	const Sbecore::uint DPCHAPPWZSKLLVLASERDO = 123;
	const Sbecore::uint DPCHAPPWZSKLLVTERMDATA = 124;
	const Sbecore::uint DPCHAPPWZSKLLVTERMDO = 125;
	const Sbecore::uint DPCHAPPWZSKLLVTTABLEDATA = 126;
	const Sbecore::uint DPCHAPPWZSKLLVTTABLEDO = 127;
	const Sbecore::uint DPCHAPPWZSKNAVADMINDATA = 128;
	const Sbecore::uint DPCHAPPWZSKNAVADMINDO = 129;
	const Sbecore::uint DPCHAPPWZSKNAVDO = 130;
	const Sbecore::uint DPCHAPPWZSKNAVGALERYDATA = 131;
	const Sbecore::uint DPCHAPPWZSKNAVGALERYDO = 132;
	const Sbecore::uint DPCHAPPWZSKNAVOPDO = 133;
	const Sbecore::uint DPCHAPPWZSKNAVPREDO = 134;
	const Sbecore::uint DPCHAPPWZSKOBJDETAILDATA = 135;
	const Sbecore::uint DPCHAPPWZSKOBJDETAILDO = 136;
	const Sbecore::uint DPCHAPPWZSKOBJDO = 137;
	const Sbecore::uint DPCHAPPWZSKOBJLISTDATA = 138;
	const Sbecore::uint DPCHAPPWZSKOBJLISTDO = 139;
	const Sbecore::uint DPCHAPPWZSKOBJRECDO = 140;
	const Sbecore::uint DPCHAPPWZSKOBJREF1NFILEDATA = 141;
	const Sbecore::uint DPCHAPPWZSKOBJREF1NFILEDO = 142;
	const Sbecore::uint DPCHAPPWZSKOGR1NOBJECTDATA = 143;
	const Sbecore::uint DPCHAPPWZSKOGR1NOBJECTDO = 144;
	const Sbecore::uint DPCHAPPWZSKOGR1NSHOTDATA = 145;
	const Sbecore::uint DPCHAPPWZSKOGR1NSHOTDO = 146;
	const Sbecore::uint DPCHAPPWZSKOGRDETAILDATA = 147;
	const Sbecore::uint DPCHAPPWZSKOGRDETAILDO = 148;
	const Sbecore::uint DPCHAPPWZSKOGRDO = 149;
	const Sbecore::uint DPCHAPPWZSKOGRLISTDATA = 150;
	const Sbecore::uint DPCHAPPWZSKOGRLISTDO = 151;
	const Sbecore::uint DPCHAPPWZSKOGRRECDO = 152;
	const Sbecore::uint DPCHAPPWZSKOGRSUP1NOBJGROUPDATA = 153;
	const Sbecore::uint DPCHAPPWZSKOGRSUP1NOBJGROUPDO = 154;
	const Sbecore::uint DPCHAPPWZSKPRSADETAILDATA = 155;
	const Sbecore::uint DPCHAPPWZSKPRSADETAILDO = 156;
	const Sbecore::uint DPCHAPPWZSKPRSDETAILDATA = 157;
	const Sbecore::uint DPCHAPPWZSKPRSDETAILDO = 158;
	const Sbecore::uint DPCHAPPWZSKPRSDO = 159;
	const Sbecore::uint DPCHAPPWZSKPRSLISTDATA = 160;
	const Sbecore::uint DPCHAPPWZSKPRSLISTDO = 161;
	const Sbecore::uint DPCHAPPWZSKPRSRECDO = 162;
	const Sbecore::uint DPCHAPPWZSKRESUME = 163;
	const Sbecore::uint DPCHAPPWZSKSCFCONNDO = 164;
	const Sbecore::uint DPCHAPPWZSKSCFDO = 165;
	const Sbecore::uint DPCHAPPWZSKSCFGEOMDO = 166;
	const Sbecore::uint DPCHAPPWZSKSES1NSHOTDATA = 167;
	const Sbecore::uint DPCHAPPWZSKSES1NSHOTDO = 168;
	const Sbecore::uint DPCHAPPWZSKSESDETAILDATA = 169;
	const Sbecore::uint DPCHAPPWZSKSESDETAILDO = 170;
	const Sbecore::uint DPCHAPPWZSKSESDO = 171;
	const Sbecore::uint DPCHAPPWZSKSESLISTDATA = 172;
	const Sbecore::uint DPCHAPPWZSKSESLISTDO = 173;
	const Sbecore::uint DPCHAPPWZSKSESRECDO = 174;
	const Sbecore::uint DPCHAPPWZSKSHTAPARDATA = 175;
	const Sbecore::uint DPCHAPPWZSKSHTAPARDO = 176;
	const Sbecore::uint DPCHAPPWZSKSHTDETAILDATA = 177;
	const Sbecore::uint DPCHAPPWZSKSHTDETAILDO = 178;
	const Sbecore::uint DPCHAPPWZSKSHTDO = 179;
	const Sbecore::uint DPCHAPPWZSKSHTLISTDATA = 180;
	const Sbecore::uint DPCHAPPWZSKSHTLISTDO = 181;
	const Sbecore::uint DPCHAPPWZSKSHTRECDO = 182;
	const Sbecore::uint DPCHAPPWZSKSHTREF1NFILEDATA = 183;
	const Sbecore::uint DPCHAPPWZSKSHTREF1NFILEDO = 184;
	const Sbecore::uint DPCHAPPWZSKUSGAACCESSDATA = 185;
	const Sbecore::uint DPCHAPPWZSKUSGAACCESSDO = 186;
	const Sbecore::uint DPCHAPPWZSKUSGDETAILDATA = 187;
	const Sbecore::uint DPCHAPPWZSKUSGDETAILDO = 188;
	const Sbecore::uint DPCHAPPWZSKUSGDO = 189;
	const Sbecore::uint DPCHAPPWZSKUSGLISTDATA = 190;
	const Sbecore::uint DPCHAPPWZSKUSGLISTDO = 191;
	const Sbecore::uint DPCHAPPWZSKUSGMNUSERDATA = 192;
	const Sbecore::uint DPCHAPPWZSKUSGMNUSERDO = 193;
	const Sbecore::uint DPCHAPPWZSKUSGRECDO = 194;
	const Sbecore::uint DPCHAPPWZSKUSR1NSESSIONDATA = 195;
	const Sbecore::uint DPCHAPPWZSKUSR1NSESSIONDO = 196;
	const Sbecore::uint DPCHAPPWZSKUSRAACCESSDATA = 197;
	const Sbecore::uint DPCHAPPWZSKUSRAACCESSDO = 198;
	const Sbecore::uint DPCHAPPWZSKUSRDETAILDATA = 199;
	const Sbecore::uint DPCHAPPWZSKUSRDETAILDO = 200;
	const Sbecore::uint DPCHAPPWZSKUSRDO = 201;
	const Sbecore::uint DPCHAPPWZSKUSRLISTDATA = 202;
	const Sbecore::uint DPCHAPPWZSKUSRLISTDO = 203;
	const Sbecore::uint DPCHAPPWZSKUSRMNUSERGROUPDATA = 204;
	const Sbecore::uint DPCHAPPWZSKUSRMNUSERGROUPDO = 205;
	const Sbecore::uint DPCHAPPWZSKUSRRECDO = 206;

	Sbecore::uint getIx(const std::string& sref);
	std::string getSref(const Sbecore::uint ix);
};

#endif

