# file Makefile.inc
# make file paths for Wzsk combined daemon, release wzskcmbd_mac
# author Catherine Johnson
# date created: 13 Oct 2020
# modified: 13 Oct 2020

SRCROOT = ${WHIZROOT}/src
LIBROOT = ${WHIZROOT}/lib
BINROOT = ${WHIZROOT}/bin
NDDSHOME = /Applications/rti_connext_dds-6.0.1
UASDKROOT =

