# file Makefile.inc
# make file paths for Wzsk combined daemon, release wzskcmbd_arty(linux (ubt_x86_64) cross-compilation)
# author Catherine Johnson
# date created: 16 Sep 2020
# modified: 16 Sep 2020

SRCROOT = ${WHIZROOT}/src
LIBROOT = ${WHIZROOT}/lib
BINROOT = ${WHIZROOT}/bin
NDDSHOME = /home/root/rti_connext_dds-6.0.1
UASDKROOT = /home/root/flex_R410_1

